/**
 * generated by Xtext 2.39.0
 */
package no.ntnu.tdt4250.bgdsl.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import no.ntnu.tdt4250.bg.Board;
import no.ntnu.tdt4250.bg.EffectPipeline;
import no.ntnu.tdt4250.bg.LegalMovesPipeline;
import no.ntnu.tdt4250.bg.State;
import no.ntnu.tdt4250.bg.Tile;
import no.ntnu.tdt4250.bg.Transition;
import no.ntnu.tdt4250.bgdsl.services.BgDslGrammarAccess;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.XbaseGenerated;

@SuppressWarnings("all")
public class BgDslFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private BgDslGrammarAccess _bgDslGrammarAccess;

  protected void _format(final Board board, @Extension final IFormattableDocument document) {
    EList<Tile> _tiles = board.getTiles();
    for (final Tile tile : _tiles) {
      document.<Tile>format(tile);
    }
    EList<LegalMovesPipeline> _legalMovesPipeline = board.getLegalMovesPipeline();
    for (final LegalMovesPipeline legalMovesPipeline : _legalMovesPipeline) {
      document.<LegalMovesPipeline>format(legalMovesPipeline);
    }
    EList<EffectPipeline> _effectPipeline = board.getEffectPipeline();
    for (final EffectPipeline effectPipeline : _effectPipeline) {
      document.<EffectPipeline>format(effectPipeline);
    }
  }

  protected void _format(final Tile tile, @Extension final IFormattableDocument document) {
    EList<State> _states = tile.getStates();
    for (final State state : _states) {
      document.<State>format(state);
    }
    EList<Transition> _transitions = tile.getTransitions();
    for (final Transition transition : _transitions) {
      document.<Transition>format(transition);
    }
    document.<State>format(tile.getInitialState());
  }

  @XbaseGenerated
  public void format(final Object board, final IFormattableDocument document) {
    if (board instanceof XtextResource) {
      _format((XtextResource)board, document);
      return;
    } else if (board instanceof Board) {
      _format((Board)board, document);
      return;
    } else if (board instanceof Tile) {
      _format((Tile)board, document);
      return;
    } else if (board instanceof EObject) {
      _format((EObject)board, document);
      return;
    } else if (board == null) {
      _format((Void)null, document);
      return;
    } else if (board != null) {
      _format(board, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(board, document).toString());
    }
  }
}
