/*
 * generated by Xtext 2.39.0
 */
package no.ntnu.tdt4250.bg.bgdsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import no.ntnu.tdt4250.bg.bgdsl.ide.contentassist.antlr.internal.InternalBgDslParser;
import no.ntnu.tdt4250.bg.bgdsl.services.BgDslGrammarAccess;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class BgDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(BgDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, BgDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getFilterAccess().getAlternatives(), "rule__Filter__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getTurnTypeAccess().getAlternatives(), "rule__TurnType__Alternatives");
			builder.put(grammarAccess.getStateSelectionAccess().getAlternatives(), "rule__StateSelection__Alternatives");
			builder.put(grammarAccess.getGameAccess().getGroup(), "rule__Game__Group__0");
			builder.put(grammarAccess.getGameAccess().getGroup_12(), "rule__Game__Group_12__0");
			builder.put(grammarAccess.getBoardAccess().getGroup(), "rule__Board__Group__0");
			builder.put(grammarAccess.getBoardAccess().getGroup_10(), "rule__Board__Group_10__0");
			builder.put(grammarAccess.getBoardAccess().getGroup_12(), "rule__Board__Group_12__0");
			builder.put(grammarAccess.getBoardAccess().getGroup_13(), "rule__Board__Group_13__0");
			builder.put(grammarAccess.getBoardAccess().getGroup_17(), "rule__Board__Group_17__0");
			builder.put(grammarAccess.getPlayerAccess().getGroup(), "rule__Player__Group__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getTileAccess().getGroup(), "rule__Tile__Group__0");
			builder.put(grammarAccess.getTileAccess().getGroup_10(), "rule__Tile__Group_10__0");
			builder.put(grammarAccess.getTileAccess().getGroup_12(), "rule__Tile__Group_12__0");
			builder.put(grammarAccess.getTileAccess().getGroup_12_3(), "rule__Tile__Group_12_3__0");
			builder.put(grammarAccess.getLegalMovesPipelineAccess().getGroup(), "rule__LegalMovesPipeline__Group__0");
			builder.put(grammarAccess.getLegalMovesPipelineAccess().getGroup_3(), "rule__LegalMovesPipeline__Group_3__0");
			builder.put(grammarAccess.getLegalMovesPipelineAccess().getGroup_3_3(), "rule__LegalMovesPipeline__Group_3_3__0");
			builder.put(grammarAccess.getEffectPipelineAccess().getGroup(), "rule__EffectPipeline__Group__0");
			builder.put(grammarAccess.getEffectPipelineAccess().getGroup_3(), "rule__EffectPipeline__Group_3__0");
			builder.put(grammarAccess.getEffectPipelineAccess().getGroup_3_3(), "rule__EffectPipeline__Group_3_3__0");
			builder.put(grammarAccess.getTilePlacementAccess().getGroup(), "rule__TilePlacement__Group__0");
			builder.put(grammarAccess.getStateAccess().getGroup(), "rule__State__Group__0");
			builder.put(grammarAccess.getStateAccess().getGroup_5(), "rule__State__Group_5__0");
			builder.put(grammarAccess.getStateAccess().getGroup_5_3(), "rule__State__Group_5_3__0");
			builder.put(grammarAccess.getStateAccess().getGroup_6(), "rule__State__Group_6__0");
			builder.put(grammarAccess.getStateAccess().getGroup_6_3(), "rule__State__Group_6_3__0");
			builder.put(grammarAccess.getTransitionAccess().getGroup(), "rule__Transition__Group__0");
			builder.put(grammarAccess.getTransitionAccess().getGroup_6(), "rule__Transition__Group_6__0");
			builder.put(grammarAccess.getPatternFilterAccess().getGroup(), "rule__PatternFilter__Group__0");
			builder.put(grammarAccess.getPatternFilterAccess().getGroup_3(), "rule__PatternFilter__Group_3__0");
			builder.put(grammarAccess.getPatternFilterAccess().getGroup_7(), "rule__PatternFilter__Group_7__0");
			builder.put(grammarAccess.getIterativeFilterAccess().getGroup(), "rule__IterativeFilter__Group__0");
			builder.put(grammarAccess.getIterativeFilterAccess().getGroup_3(), "rule__IterativeFilter__Group_3__0");
			builder.put(grammarAccess.getStateEffectFilterAccess().getGroup(), "rule__StateEffectFilter__Group__0");
			builder.put(grammarAccess.getStateEffectFilterAccess().getGroup_5(), "rule__StateEffectFilter__Group_5__0");
			builder.put(grammarAccess.getStateEffectFilterAccess().getGroup_6(), "rule__StateEffectFilter__Group_6__0");
			builder.put(grammarAccess.getWinConditionFilterAccess().getGroup(), "rule__WinConditionFilter__Group__0");
			builder.put(grammarAccess.getWinConditionFilterAccess().getGroup_3(), "rule__WinConditionFilter__Group_3__0");
			builder.put(grammarAccess.getWinConditionFilterAccess().getGroup_7(), "rule__WinConditionFilter__Group_7__0");
			builder.put(grammarAccess.getPatternAccess().getGroup(), "rule__Pattern__Group__0");
			builder.put(grammarAccess.getPatternAccess().getGroup_3(), "rule__Pattern__Group_3__0");
			builder.put(grammarAccess.getPatternAccess().getGroup_4(), "rule__Pattern__Group_4__0");
			builder.put(grammarAccess.getPatternAccess().getGroup_8(), "rule__Pattern__Group_8__0");
			builder.put(grammarAccess.getRelativeCoordinateAccess().getGroup(), "rule__RelativeCoordinate__Group__0");
			builder.put(grammarAccess.getGameAccess().getNameAssignment_1(), "rule__Game__NameAssignment_1");
			builder.put(grammarAccess.getGameAccess().getTurnPolicyAssignment_4(), "rule__Game__TurnPolicyAssignment_4");
			builder.put(grammarAccess.getGameAccess().getInitialPlayerAssignment_6(), "rule__Game__InitialPlayerAssignment_6");
			builder.put(grammarAccess.getGameAccess().getBoardAssignment_8(), "rule__Game__BoardAssignment_8");
			builder.put(grammarAccess.getGameAccess().getPlayersAssignment_11(), "rule__Game__PlayersAssignment_11");
			builder.put(grammarAccess.getGameAccess().getPlayersAssignment_12_1(), "rule__Game__PlayersAssignment_12_1");
			builder.put(grammarAccess.getBoardAccess().getCheckeredAssignment_0(), "rule__Board__CheckeredAssignment_0");
			builder.put(grammarAccess.getBoardAccess().getWidthAssignment_4(), "rule__Board__WidthAssignment_4");
			builder.put(grammarAccess.getBoardAccess().getHeightAssignment_6(), "rule__Board__HeightAssignment_6");
			builder.put(grammarAccess.getBoardAccess().getTilesAssignment_9(), "rule__Board__TilesAssignment_9");
			builder.put(grammarAccess.getBoardAccess().getTilesAssignment_10_1(), "rule__Board__TilesAssignment_10_1");
			builder.put(grammarAccess.getBoardAccess().getLegalMovesPipelineAssignment_12_1(), "rule__Board__LegalMovesPipelineAssignment_12_1");
			builder.put(grammarAccess.getBoardAccess().getEffectPipelineAssignment_13_1(), "rule__Board__EffectPipelineAssignment_13_1");
			builder.put(grammarAccess.getBoardAccess().getTileplacementAssignment_16(), "rule__Board__TileplacementAssignment_16");
			builder.put(grammarAccess.getBoardAccess().getTileplacementAssignment_17_1(), "rule__Board__TileplacementAssignment_17_1");
			builder.put(grammarAccess.getPlayerAccess().getNameAssignment_1(), "rule__Player__NameAssignment_1");
			builder.put(grammarAccess.getPlayerAccess().getHexColorAssignment_4(), "rule__Player__HexColorAssignment_4");
			builder.put(grammarAccess.getPlayerAccess().getAssociatedStateAssignment_6(), "rule__Player__AssociatedStateAssignment_6");
			builder.put(grammarAccess.getTileAccess().getTileTypeAssignment_1(), "rule__Tile__TileTypeAssignment_1");
			builder.put(grammarAccess.getTileAccess().getHexColorAssignment_4(), "rule__Tile__HexColorAssignment_4");
			builder.put(grammarAccess.getTileAccess().getNameAssignment_6(), "rule__Tile__NameAssignment_6");
			builder.put(grammarAccess.getTileAccess().getStatesAssignment_9(), "rule__Tile__StatesAssignment_9");
			builder.put(grammarAccess.getTileAccess().getStatesAssignment_10_1(), "rule__Tile__StatesAssignment_10_1");
			builder.put(grammarAccess.getTileAccess().getTransitionsAssignment_12_2(), "rule__Tile__TransitionsAssignment_12_2");
			builder.put(grammarAccess.getTileAccess().getTransitionsAssignment_12_3_1(), "rule__Tile__TransitionsAssignment_12_3_1");
			builder.put(grammarAccess.getTileAccess().getInitialStateAssignment_14(), "rule__Tile__InitialStateAssignment_14");
			builder.put(grammarAccess.getLegalMovesPipelineAccess().getFiltersAssignment_3_2(), "rule__LegalMovesPipeline__FiltersAssignment_3_2");
			builder.put(grammarAccess.getLegalMovesPipelineAccess().getFiltersAssignment_3_3_1(), "rule__LegalMovesPipeline__FiltersAssignment_3_3_1");
			builder.put(grammarAccess.getEffectPipelineAccess().getFiltersAssignment_3_2(), "rule__EffectPipeline__FiltersAssignment_3_2");
			builder.put(grammarAccess.getEffectPipelineAccess().getFiltersAssignment_3_3_1(), "rule__EffectPipeline__FiltersAssignment_3_3_1");
			builder.put(grammarAccess.getTilePlacementAccess().getRowAssignment_3(), "rule__TilePlacement__RowAssignment_3");
			builder.put(grammarAccess.getTilePlacementAccess().getColumnAssignment_5(), "rule__TilePlacement__ColumnAssignment_5");
			builder.put(grammarAccess.getTilePlacementAccess().getTileAssignment_7(), "rule__TilePlacement__TileAssignment_7");
			builder.put(grammarAccess.getStateAccess().getNameAssignment_1(), "rule__State__NameAssignment_1");
			builder.put(grammarAccess.getStateAccess().getHexColorAssignment_4(), "rule__State__HexColorAssignment_4");
			builder.put(grammarAccess.getStateAccess().getOutboundAssignment_5_2(), "rule__State__OutboundAssignment_5_2");
			builder.put(grammarAccess.getStateAccess().getOutboundAssignment_5_3_1(), "rule__State__OutboundAssignment_5_3_1");
			builder.put(grammarAccess.getStateAccess().getInboundAssignment_6_2(), "rule__State__InboundAssignment_6_2");
			builder.put(grammarAccess.getStateAccess().getInboundAssignment_6_3_1(), "rule__State__InboundAssignment_6_3_1");
			builder.put(grammarAccess.getTransitionAccess().getNameAssignment_1(), "rule__Transition__NameAssignment_1");
			builder.put(grammarAccess.getTransitionAccess().getSourceAssignment_5(), "rule__Transition__SourceAssignment_5");
			builder.put(grammarAccess.getTransitionAccess().getSourceAssignment_6_1(), "rule__Transition__SourceAssignment_6_1");
			builder.put(grammarAccess.getTransitionAccess().getTargetAssignment_9(), "rule__Transition__TargetAssignment_9");
			builder.put(grammarAccess.getPatternFilterAccess().getNameAssignment_1(), "rule__PatternFilter__NameAssignment_1");
			builder.put(grammarAccess.getPatternFilterAccess().getNextFilterAssignment_3_1(), "rule__PatternFilter__NextFilterAssignment_3_1");
			builder.put(grammarAccess.getPatternFilterAccess().getPatternsAssignment_6(), "rule__PatternFilter__PatternsAssignment_6");
			builder.put(grammarAccess.getPatternFilterAccess().getPatternsAssignment_7_1(), "rule__PatternFilter__PatternsAssignment_7_1");
			builder.put(grammarAccess.getIterativeFilterAccess().getNameAssignment_1(), "rule__IterativeFilter__NameAssignment_1");
			builder.put(grammarAccess.getIterativeFilterAccess().getNextFilterAssignment_3_1(), "rule__IterativeFilter__NextFilterAssignment_3_1");
			builder.put(grammarAccess.getIterativeFilterAccess().getDirectionVectorAssignment_5(), "rule__IterativeFilter__DirectionVectorAssignment_5");
			builder.put(grammarAccess.getIterativeFilterAccess().getMatchRuleAssignment_7(), "rule__IterativeFilter__MatchRuleAssignment_7");
			builder.put(grammarAccess.getIterativeFilterAccess().getEndRuleAssignment_9(), "rule__IterativeFilter__EndRuleAssignment_9");
			builder.put(grammarAccess.getStateEffectFilterAccess().getNameAssignment_1(), "rule__StateEffectFilter__NameAssignment_1");
			builder.put(grammarAccess.getStateEffectFilterAccess().getStateSelectionAssignment_4(), "rule__StateEffectFilter__StateSelectionAssignment_4");
			builder.put(grammarAccess.getStateEffectFilterAccess().getTargetStateAssignment_5_1(), "rule__StateEffectFilter__TargetStateAssignment_5_1");
			builder.put(grammarAccess.getStateEffectFilterAccess().getNextFilterAssignment_6_1(), "rule__StateEffectFilter__NextFilterAssignment_6_1");
			builder.put(grammarAccess.getWinConditionFilterAccess().getNameAssignment_1(), "rule__WinConditionFilter__NameAssignment_1");
			builder.put(grammarAccess.getWinConditionFilterAccess().getNextFilterAssignment_3_1(), "rule__WinConditionFilter__NextFilterAssignment_3_1");
			builder.put(grammarAccess.getWinConditionFilterAccess().getPatternsAssignment_6(), "rule__WinConditionFilter__PatternsAssignment_6");
			builder.put(grammarAccess.getWinConditionFilterAccess().getPatternsAssignment_7_1(), "rule__WinConditionFilter__PatternsAssignment_7_1");
			builder.put(grammarAccess.getPatternAccess().getNameAssignment_1(), "rule__Pattern__NameAssignment_1");
			builder.put(grammarAccess.getPatternAccess().getStateSelectionAssignment_3_1(), "rule__Pattern__StateSelectionAssignment_3_1");
			builder.put(grammarAccess.getPatternAccess().getMatchStateAssignment_4_1(), "rule__Pattern__MatchStateAssignment_4_1");
			builder.put(grammarAccess.getPatternAccess().getRelativecoordinatesAssignment_7(), "rule__Pattern__RelativecoordinatesAssignment_7");
			builder.put(grammarAccess.getPatternAccess().getRelativecoordinatesAssignment_8_1(), "rule__Pattern__RelativecoordinatesAssignment_8_1");
			builder.put(grammarAccess.getRelativeCoordinateAccess().getXAssignment_3(), "rule__RelativeCoordinate__XAssignment_3");
			builder.put(grammarAccess.getRelativeCoordinateAccess().getYAssignment_5(), "rule__RelativeCoordinate__YAssignment_5");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private BgDslGrammarAccess grammarAccess;

	@Override
	protected InternalBgDslParser createParser() {
		InternalBgDslParser result = new InternalBgDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public BgDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BgDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
