/*
 * generated by Xtext 2.41.0
 */
package no.ntnu.tdt4250.bg.bgdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBgDslScopeProvider extends DelegatingScopeProvider {
}
