/*
 * generated by Xtext 2.39.0
 */
package no.ntnu.tdt4250.bg.bgdsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class BgDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class GameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bg.bgdsl.BgDsl.Game");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGameKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cInitialPlayerKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cInitialPlayerAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cInitialPlayerPlayerCrossReference_3_1_0 = (CrossReference)cInitialPlayerAssignment_3_1.eContents().get(0);
		private final RuleCall cInitialPlayerPlayerEStringParserRuleCall_3_1_0_1 = (RuleCall)cInitialPlayerPlayerCrossReference_3_1_0.eContents().get(1);
		private final Keyword cBoardKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cBoardAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cBoardBoardParserRuleCall_5_0 = (RuleCall)cBoardAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cPlayersKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cPlayersAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cPlayersPlayerParserRuleCall_6_2_0 = (RuleCall)cPlayersAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cPlayersAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cPlayersPlayerParserRuleCall_6_3_1_0 = (RuleCall)cPlayersAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cTurnPolicyKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cTurnPolicyAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cTurnPolicyTurnTypeEnumRuleCall_8_0 = (RuleCall)cTurnPolicyAssignment_8.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Game returns Game:
		//    'Game'
		//    name=EString
		//    '{'
		//        ('initialPlayer' initialPlayer=[Player|EString])?
		//        'board' board=Board
		//        ('players' '{' players+=Player ( "," players+=Player)* '}' )?
		//        'turnPolicy' turnPolicy=TurnType
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Game'
		//name=EString
		//'{'
		//    ('initialPlayer' initialPlayer=[Player|EString])?
		//    'board' board=Board
		//    ('players' '{' players+=Player ( "," players+=Player)* '}' )?
		//    'turnPolicy' turnPolicy=TurnType
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Game'
		public Keyword getGameKeyword_0() { return cGameKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('initialPlayer' initialPlayer=[Player|EString])?
		public Group getGroup_3() { return cGroup_3; }
		
		//'initialPlayer'
		public Keyword getInitialPlayerKeyword_3_0() { return cInitialPlayerKeyword_3_0; }
		
		//initialPlayer=[Player|EString]
		public Assignment getInitialPlayerAssignment_3_1() { return cInitialPlayerAssignment_3_1; }
		
		//[Player|EString]
		public CrossReference getInitialPlayerPlayerCrossReference_3_1_0() { return cInitialPlayerPlayerCrossReference_3_1_0; }
		
		//EString
		public RuleCall getInitialPlayerPlayerEStringParserRuleCall_3_1_0_1() { return cInitialPlayerPlayerEStringParserRuleCall_3_1_0_1; }
		
		//'board'
		public Keyword getBoardKeyword_4() { return cBoardKeyword_4; }
		
		//board=Board
		public Assignment getBoardAssignment_5() { return cBoardAssignment_5; }
		
		//Board
		public RuleCall getBoardBoardParserRuleCall_5_0() { return cBoardBoardParserRuleCall_5_0; }
		
		//('players' '{' players+=Player ( "," players+=Player)* '}' )?
		public Group getGroup_6() { return cGroup_6; }
		
		//'players'
		public Keyword getPlayersKeyword_6_0() { return cPlayersKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//players+=Player
		public Assignment getPlayersAssignment_6_2() { return cPlayersAssignment_6_2; }
		
		//Player
		public RuleCall getPlayersPlayerParserRuleCall_6_2_0() { return cPlayersPlayerParserRuleCall_6_2_0; }
		
		//( "," players+=Player)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//players+=Player
		public Assignment getPlayersAssignment_6_3_1() { return cPlayersAssignment_6_3_1; }
		
		//Player
		public RuleCall getPlayersPlayerParserRuleCall_6_3_1_0() { return cPlayersPlayerParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//'turnPolicy'
		public Keyword getTurnPolicyKeyword_7() { return cTurnPolicyKeyword_7; }
		
		//turnPolicy=TurnType
		public Assignment getTurnPolicyAssignment_8() { return cTurnPolicyAssignment_8; }
		
		//TurnType
		public RuleCall getTurnPolicyTurnTypeEnumRuleCall_8_0() { return cTurnPolicyTurnTypeEnumRuleCall_8_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class FilterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bg.bgdsl.BgDsl.Filter");
		private final RuleCall cPatternFilterParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Filter returns Filter:
		//    PatternFilter;
		@Override public ParserRule getRule() { return rule; }
		
		//PatternFilter
		public RuleCall getPatternFilterParserRuleCall() { return cPatternFilterParserRuleCall; }
	}
	public class BoardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bg.bgdsl.BgDsl.Board");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cCheckeredAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cCheckeredCheckeredKeyword_0_0 = (Keyword)cCheckeredAssignment_0.eContents().get(0);
		private final Keyword cBoardKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cWidthKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cWidthAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cWidthEIntParserRuleCall_4_0 = (RuleCall)cWidthAssignment_4.eContents().get(0);
		private final Keyword cHeightKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cHeightAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cHeightEIntParserRuleCall_6_0 = (RuleCall)cHeightAssignment_6.eContents().get(0);
		private final Keyword cTilesKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cLeftCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cTilesAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cTilesTileParserRuleCall_9_0 = (RuleCall)cTilesAssignment_9.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cCommaKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cTilesAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cTilesTileParserRuleCall_10_1_0 = (RuleCall)cTilesAssignment_10_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cLegalMovesPipelineKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cLegalMovesPipelineAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final RuleCall cLegalMovesPipelineLegalMovesPipelineParserRuleCall_12_1_0 = (RuleCall)cLegalMovesPipelineAssignment_12_1.eContents().get(0);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Keyword cEffectPipelineKeyword_13_0 = (Keyword)cGroup_13.eContents().get(0);
		private final Assignment cEffectPipelineAssignment_13_1 = (Assignment)cGroup_13.eContents().get(1);
		private final RuleCall cEffectPipelineEffectPipelineParserRuleCall_13_1_0 = (RuleCall)cEffectPipelineAssignment_13_1.eContents().get(0);
		private final Keyword cTileplacementKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Keyword cLeftCurlyBracketKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Assignment cTileplacementAssignment_16 = (Assignment)cGroup.eContents().get(16);
		private final RuleCall cTileplacementTilePlacementParserRuleCall_16_0 = (RuleCall)cTileplacementAssignment_16.eContents().get(0);
		private final Group cGroup_17 = (Group)cGroup.eContents().get(17);
		private final Keyword cCommaKeyword_17_0 = (Keyword)cGroup_17.eContents().get(0);
		private final Assignment cTileplacementAssignment_17_1 = (Assignment)cGroup_17.eContents().get(1);
		private final RuleCall cTileplacementTilePlacementParserRuleCall_17_1_0 = (RuleCall)cTileplacementAssignment_17_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_18 = (Keyword)cGroup.eContents().get(18);
		private final Keyword cRightCurlyBracketKeyword_19 = (Keyword)cGroup.eContents().get(19);
		
		//Board returns Board:
		//    checkered?='checkered'
		//    'Board'
		//    '{'
		//        'width' width=EInt
		//        'height' height=EInt
		//        'tiles' '{' tiles+=Tile ( "," tiles+=Tile)* '}'
		//        ('legalMovesPipeline' legalMovesPipeline=LegalMovesPipeline)?
		//        ('effectPipeline'effectPipeline=EffectPipeline)?
		//        'tileplacement' '{' tileplacement+=TilePlacement ( "," tileplacement+=TilePlacement)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//checkered?='checkered'
		//'Board'
		//'{'
		//    'width' width=EInt
		//    'height' height=EInt
		//    'tiles' '{' tiles+=Tile ( "," tiles+=Tile)* '}'
		//    ('legalMovesPipeline' legalMovesPipeline=LegalMovesPipeline)?
		//    ('effectPipeline'effectPipeline=EffectPipeline)?
		//    'tileplacement' '{' tileplacement+=TilePlacement ( "," tileplacement+=TilePlacement)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//checkered?='checkered'
		public Assignment getCheckeredAssignment_0() { return cCheckeredAssignment_0; }
		
		//'checkered'
		public Keyword getCheckeredCheckeredKeyword_0_0() { return cCheckeredCheckeredKeyword_0_0; }
		
		//'Board'
		public Keyword getBoardKeyword_1() { return cBoardKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'width'
		public Keyword getWidthKeyword_3() { return cWidthKeyword_3; }
		
		//width=EInt
		public Assignment getWidthAssignment_4() { return cWidthAssignment_4; }
		
		//EInt
		public RuleCall getWidthEIntParserRuleCall_4_0() { return cWidthEIntParserRuleCall_4_0; }
		
		//'height'
		public Keyword getHeightKeyword_5() { return cHeightKeyword_5; }
		
		//height=EInt
		public Assignment getHeightAssignment_6() { return cHeightAssignment_6; }
		
		//EInt
		public RuleCall getHeightEIntParserRuleCall_6_0() { return cHeightEIntParserRuleCall_6_0; }
		
		//'tiles'
		public Keyword getTilesKeyword_7() { return cTilesKeyword_7; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_8() { return cLeftCurlyBracketKeyword_8; }
		
		//tiles+=Tile
		public Assignment getTilesAssignment_9() { return cTilesAssignment_9; }
		
		//Tile
		public RuleCall getTilesTileParserRuleCall_9_0() { return cTilesTileParserRuleCall_9_0; }
		
		//( "," tiles+=Tile)*
		public Group getGroup_10() { return cGroup_10; }
		
		//","
		public Keyword getCommaKeyword_10_0() { return cCommaKeyword_10_0; }
		
		//tiles+=Tile
		public Assignment getTilesAssignment_10_1() { return cTilesAssignment_10_1; }
		
		//Tile
		public RuleCall getTilesTileParserRuleCall_10_1_0() { return cTilesTileParserRuleCall_10_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
		
		//('legalMovesPipeline' legalMovesPipeline=LegalMovesPipeline)?
		public Group getGroup_12() { return cGroup_12; }
		
		//'legalMovesPipeline'
		public Keyword getLegalMovesPipelineKeyword_12_0() { return cLegalMovesPipelineKeyword_12_0; }
		
		//legalMovesPipeline=LegalMovesPipeline
		public Assignment getLegalMovesPipelineAssignment_12_1() { return cLegalMovesPipelineAssignment_12_1; }
		
		//LegalMovesPipeline
		public RuleCall getLegalMovesPipelineLegalMovesPipelineParserRuleCall_12_1_0() { return cLegalMovesPipelineLegalMovesPipelineParserRuleCall_12_1_0; }
		
		//('effectPipeline'effectPipeline=EffectPipeline)?
		public Group getGroup_13() { return cGroup_13; }
		
		//'effectPipeline'
		public Keyword getEffectPipelineKeyword_13_0() { return cEffectPipelineKeyword_13_0; }
		
		//effectPipeline=EffectPipeline
		public Assignment getEffectPipelineAssignment_13_1() { return cEffectPipelineAssignment_13_1; }
		
		//EffectPipeline
		public RuleCall getEffectPipelineEffectPipelineParserRuleCall_13_1_0() { return cEffectPipelineEffectPipelineParserRuleCall_13_1_0; }
		
		//'tileplacement'
		public Keyword getTileplacementKeyword_14() { return cTileplacementKeyword_14; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_15() { return cLeftCurlyBracketKeyword_15; }
		
		//tileplacement+=TilePlacement
		public Assignment getTileplacementAssignment_16() { return cTileplacementAssignment_16; }
		
		//TilePlacement
		public RuleCall getTileplacementTilePlacementParserRuleCall_16_0() { return cTileplacementTilePlacementParserRuleCall_16_0; }
		
		//( "," tileplacement+=TilePlacement)*
		public Group getGroup_17() { return cGroup_17; }
		
		//","
		public Keyword getCommaKeyword_17_0() { return cCommaKeyword_17_0; }
		
		//tileplacement+=TilePlacement
		public Assignment getTileplacementAssignment_17_1() { return cTileplacementAssignment_17_1; }
		
		//TilePlacement
		public RuleCall getTileplacementTilePlacementParserRuleCall_17_1_0() { return cTileplacementTilePlacementParserRuleCall_17_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_18() { return cRightCurlyBracketKeyword_18; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_19() { return cRightCurlyBracketKeyword_19; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bg.bgdsl.BgDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class PlayerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bg.bgdsl.BgDsl.Player");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPlayerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cHexColorKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cHexColorAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cHexColorEStringParserRuleCall_4_0 = (RuleCall)cHexColorAssignment_4.eContents().get(0);
		private final Keyword cAssociatedStateKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cAssociatedStateAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cAssociatedStateStateCrossReference_6_0 = (CrossReference)cAssociatedStateAssignment_6.eContents().get(0);
		private final RuleCall cAssociatedStateStateEStringParserRuleCall_6_0_1 = (RuleCall)cAssociatedStateStateCrossReference_6_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Player returns Player:
		//    'Player'
		//    name=EString
		//    '{'
		//        'hexColor' hexColor=EString
		//        'associatedState' associatedState=[State|EString]
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Player'
		//name=EString
		//'{'
		//    'hexColor' hexColor=EString
		//    'associatedState' associatedState=[State|EString]
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Player'
		public Keyword getPlayerKeyword_0() { return cPlayerKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'hexColor'
		public Keyword getHexColorKeyword_3() { return cHexColorKeyword_3; }
		
		//hexColor=EString
		public Assignment getHexColorAssignment_4() { return cHexColorAssignment_4; }
		
		//EString
		public RuleCall getHexColorEStringParserRuleCall_4_0() { return cHexColorEStringParserRuleCall_4_0; }
		
		//'associatedState'
		public Keyword getAssociatedStateKeyword_5() { return cAssociatedStateKeyword_5; }
		
		//associatedState=[State|EString]
		public Assignment getAssociatedStateAssignment_6() { return cAssociatedStateAssignment_6; }
		
		//[State|EString]
		public CrossReference getAssociatedStateStateCrossReference_6_0() { return cAssociatedStateStateCrossReference_6_0; }
		
		//EString
		public RuleCall getAssociatedStateStateEStringParserRuleCall_6_0_1() { return cAssociatedStateStateEStringParserRuleCall_6_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bg.bgdsl.BgDsl.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class TileElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bg.bgdsl.BgDsl.Tile");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTileKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeEStringParserRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cHexColorKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cHexColorAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cHexColorEStringParserRuleCall_4_0 = (RuleCall)cHexColorAssignment_4.eContents().get(0);
		private final Keyword cNameKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cNameAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cNameEStringParserRuleCall_6_0 = (RuleCall)cNameAssignment_6.eContents().get(0);
		private final Keyword cStatesKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cLeftCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cStatesAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cStatesStateParserRuleCall_9_0 = (RuleCall)cStatesAssignment_9.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cCommaKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cStatesAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cStatesStateParserRuleCall_10_1_0 = (RuleCall)cStatesAssignment_10_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cTransitionsKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_12_1 = (Keyword)cGroup_12.eContents().get(1);
		private final Assignment cTransitionsAssignment_12_2 = (Assignment)cGroup_12.eContents().get(2);
		private final RuleCall cTransitionsTransitionParserRuleCall_12_2_0 = (RuleCall)cTransitionsAssignment_12_2.eContents().get(0);
		private final Group cGroup_12_3 = (Group)cGroup_12.eContents().get(3);
		private final Keyword cCommaKeyword_12_3_0 = (Keyword)cGroup_12_3.eContents().get(0);
		private final Assignment cTransitionsAssignment_12_3_1 = (Assignment)cGroup_12_3.eContents().get(1);
		private final RuleCall cTransitionsTransitionParserRuleCall_12_3_1_0 = (RuleCall)cTransitionsAssignment_12_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12_4 = (Keyword)cGroup_12.eContents().get(4);
		private final Keyword cInitialStateKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cInitialStateAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cInitialStateStateParserRuleCall_14_0 = (RuleCall)cInitialStateAssignment_14.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_15 = (Keyword)cGroup.eContents().get(15);
		
		//Tile returns Tile:
		//    'Tile'
		//    type=EString
		//    '{'
		//        'hexColor' hexColor=EString
		//        'name' name=EString
		//        'states' '{' states+=State ( "," states+=State)* '}'
		//        ('transitions' '{' transitions+=Transition ( "," transitions+=Transition)* '}' )?
		//        'initialState' initialState=State
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Tile'
		//type=EString
		//'{'
		//    'hexColor' hexColor=EString
		//    'name' name=EString
		//    'states' '{' states+=State ( "," states+=State)* '}'
		//    ('transitions' '{' transitions+=Transition ( "," transitions+=Transition)* '}' )?
		//    'initialState' initialState=State
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Tile'
		public Keyword getTileKeyword_0() { return cTileKeyword_0; }
		
		//type=EString
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//EString
		public RuleCall getTypeEStringParserRuleCall_1_0() { return cTypeEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'hexColor'
		public Keyword getHexColorKeyword_3() { return cHexColorKeyword_3; }
		
		//hexColor=EString
		public Assignment getHexColorAssignment_4() { return cHexColorAssignment_4; }
		
		//EString
		public RuleCall getHexColorEStringParserRuleCall_4_0() { return cHexColorEStringParserRuleCall_4_0; }
		
		//'name'
		public Keyword getNameKeyword_5() { return cNameKeyword_5; }
		
		//name=EString
		public Assignment getNameAssignment_6() { return cNameAssignment_6; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_6_0() { return cNameEStringParserRuleCall_6_0; }
		
		//'states'
		public Keyword getStatesKeyword_7() { return cStatesKeyword_7; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_8() { return cLeftCurlyBracketKeyword_8; }
		
		//states+=State
		public Assignment getStatesAssignment_9() { return cStatesAssignment_9; }
		
		//State
		public RuleCall getStatesStateParserRuleCall_9_0() { return cStatesStateParserRuleCall_9_0; }
		
		//( "," states+=State)*
		public Group getGroup_10() { return cGroup_10; }
		
		//","
		public Keyword getCommaKeyword_10_0() { return cCommaKeyword_10_0; }
		
		//states+=State
		public Assignment getStatesAssignment_10_1() { return cStatesAssignment_10_1; }
		
		//State
		public RuleCall getStatesStateParserRuleCall_10_1_0() { return cStatesStateParserRuleCall_10_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
		
		//('transitions' '{' transitions+=Transition ( "," transitions+=Transition)* '}' )?
		public Group getGroup_12() { return cGroup_12; }
		
		//'transitions'
		public Keyword getTransitionsKeyword_12_0() { return cTransitionsKeyword_12_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_12_1() { return cLeftCurlyBracketKeyword_12_1; }
		
		//transitions+=Transition
		public Assignment getTransitionsAssignment_12_2() { return cTransitionsAssignment_12_2; }
		
		//Transition
		public RuleCall getTransitionsTransitionParserRuleCall_12_2_0() { return cTransitionsTransitionParserRuleCall_12_2_0; }
		
		//( "," transitions+=Transition)*
		public Group getGroup_12_3() { return cGroup_12_3; }
		
		//","
		public Keyword getCommaKeyword_12_3_0() { return cCommaKeyword_12_3_0; }
		
		//transitions+=Transition
		public Assignment getTransitionsAssignment_12_3_1() { return cTransitionsAssignment_12_3_1; }
		
		//Transition
		public RuleCall getTransitionsTransitionParserRuleCall_12_3_1_0() { return cTransitionsTransitionParserRuleCall_12_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12_4() { return cRightCurlyBracketKeyword_12_4; }
		
		//'initialState'
		public Keyword getInitialStateKeyword_13() { return cInitialStateKeyword_13; }
		
		//initialState=State
		public Assignment getInitialStateAssignment_14() { return cInitialStateAssignment_14; }
		
		//State
		public RuleCall getInitialStateStateParserRuleCall_14_0() { return cInitialStateStateParserRuleCall_14_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_15() { return cRightCurlyBracketKeyword_15; }
	}
	public class LegalMovesPipelineElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bg.bgdsl.BgDsl.LegalMovesPipeline");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cLegalMovesPipelineAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLegalMovesPipelineKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cFilterKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cFilterAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cFilterFilterParserRuleCall_3_1_0 = (RuleCall)cFilterAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//LegalMovesPipeline returns LegalMovesPipeline:
		//    {LegalMovesPipeline}
		//    'LegalMovesPipeline'
		//    '{'
		//        ('filter' filter=Filter)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{LegalMovesPipeline}
		//'LegalMovesPipeline'
		//'{'
		//    ('filter' filter=Filter)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{LegalMovesPipeline}
		public Action getLegalMovesPipelineAction_0() { return cLegalMovesPipelineAction_0; }
		
		//'LegalMovesPipeline'
		public Keyword getLegalMovesPipelineKeyword_1() { return cLegalMovesPipelineKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('filter' filter=Filter)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'filter'
		public Keyword getFilterKeyword_3_0() { return cFilterKeyword_3_0; }
		
		//filter=Filter
		public Assignment getFilterAssignment_3_1() { return cFilterAssignment_3_1; }
		
		//Filter
		public RuleCall getFilterFilterParserRuleCall_3_1_0() { return cFilterFilterParserRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class EffectPipelineElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bg.bgdsl.BgDsl.EffectPipeline");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEffectPipelineAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cEffectPipelineKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cFilterKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cFilterAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cFilterFilterParserRuleCall_3_1_0 = (RuleCall)cFilterAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//EffectPipeline returns EffectPipeline:
		//    {EffectPipeline}
		//    'EffectPipeline'
		//    '{'
		//        ('filter' filter=Filter)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{EffectPipeline}
		//'EffectPipeline'
		//'{'
		//    ('filter' filter=Filter)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{EffectPipeline}
		public Action getEffectPipelineAction_0() { return cEffectPipelineAction_0; }
		
		//'EffectPipeline'
		public Keyword getEffectPipelineKeyword_1() { return cEffectPipelineKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('filter' filter=Filter)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'filter'
		public Keyword getFilterKeyword_3_0() { return cFilterKeyword_3_0; }
		
		//filter=Filter
		public Assignment getFilterAssignment_3_1() { return cFilterAssignment_3_1; }
		
		//Filter
		public RuleCall getFilterFilterParserRuleCall_3_1_0() { return cFilterFilterParserRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bg.bgdsl.BgDsl.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//    'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class TilePlacementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bg.bgdsl.BgDsl.TilePlacement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTilePlacementKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cRowKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cRowAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cRowEIntParserRuleCall_3_0 = (RuleCall)cRowAssignment_3.eContents().get(0);
		private final Keyword cColumnKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cColumnAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cColumnEIntParserRuleCall_5_0 = (RuleCall)cColumnAssignment_5.eContents().get(0);
		private final Keyword cTileKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cTileAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cTileTileCrossReference_7_0 = (CrossReference)cTileAssignment_7.eContents().get(0);
		private final RuleCall cTileTileEStringParserRuleCall_7_0_1 = (RuleCall)cTileTileCrossReference_7_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//TilePlacement returns TilePlacement:
		//    'TilePlacement'
		//    '{'
		//        'row' row=EInt
		//        'column' column=EInt
		//        'tile' tile=[Tile|EString]
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'TilePlacement'
		//'{'
		//    'row' row=EInt
		//    'column' column=EInt
		//    'tile' tile=[Tile|EString]
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'TilePlacement'
		public Keyword getTilePlacementKeyword_0() { return cTilePlacementKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'row'
		public Keyword getRowKeyword_2() { return cRowKeyword_2; }
		
		//row=EInt
		public Assignment getRowAssignment_3() { return cRowAssignment_3; }
		
		//EInt
		public RuleCall getRowEIntParserRuleCall_3_0() { return cRowEIntParserRuleCall_3_0; }
		
		//'column'
		public Keyword getColumnKeyword_4() { return cColumnKeyword_4; }
		
		//column=EInt
		public Assignment getColumnAssignment_5() { return cColumnAssignment_5; }
		
		//EInt
		public RuleCall getColumnEIntParserRuleCall_5_0() { return cColumnEIntParserRuleCall_5_0; }
		
		//'tile'
		public Keyword getTileKeyword_6() { return cTileKeyword_6; }
		
		//tile=[Tile|EString]
		public Assignment getTileAssignment_7() { return cTileAssignment_7; }
		
		//[Tile|EString]
		public CrossReference getTileTileCrossReference_7_0() { return cTileTileCrossReference_7_0; }
		
		//EString
		public RuleCall getTileTileEStringParserRuleCall_7_0_1() { return cTileTileEStringParserRuleCall_7_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class StateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bg.bgdsl.BgDsl.State");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStateKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cHexColorKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cHexColorAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cHexColorEStringParserRuleCall_4_0 = (RuleCall)cHexColorAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cOutboundKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cOutboundAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cOutboundTransitionCrossReference_5_2_0 = (CrossReference)cOutboundAssignment_5_2.eContents().get(0);
		private final RuleCall cOutboundTransitionEStringParserRuleCall_5_2_0_1 = (RuleCall)cOutboundTransitionCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cOutboundAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cOutboundTransitionCrossReference_5_3_1_0 = (CrossReference)cOutboundAssignment_5_3_1.eContents().get(0);
		private final RuleCall cOutboundTransitionEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cOutboundTransitionCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cInboundKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cInboundAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final CrossReference cInboundTransitionCrossReference_6_2_0 = (CrossReference)cInboundAssignment_6_2.eContents().get(0);
		private final RuleCall cInboundTransitionEStringParserRuleCall_6_2_0_1 = (RuleCall)cInboundTransitionCrossReference_6_2_0.eContents().get(1);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cInboundAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final CrossReference cInboundTransitionCrossReference_6_3_1_0 = (CrossReference)cInboundAssignment_6_3_1.eContents().get(0);
		private final RuleCall cInboundTransitionEStringParserRuleCall_6_3_1_0_1 = (RuleCall)cInboundTransitionCrossReference_6_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//State returns State:
		//    'State'
		//    name=EString
		//    '{'
		//        'hexColor' hexColor=EString
		//        ('outbound' '(' outbound+=[Transition|EString] ( "," outbound+=[Transition|EString])* ')' )?
		//        ('inbound' '(' inbound+=[Transition|EString] ( "," inbound+=[Transition|EString])* ')' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'State'
		//name=EString
		//'{'
		//    'hexColor' hexColor=EString
		//    ('outbound' '(' outbound+=[Transition|EString] ( "," outbound+=[Transition|EString])* ')' )?
		//    ('inbound' '(' inbound+=[Transition|EString] ( "," inbound+=[Transition|EString])* ')' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'State'
		public Keyword getStateKeyword_0() { return cStateKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'hexColor'
		public Keyword getHexColorKeyword_3() { return cHexColorKeyword_3; }
		
		//hexColor=EString
		public Assignment getHexColorAssignment_4() { return cHexColorAssignment_4; }
		
		//EString
		public RuleCall getHexColorEStringParserRuleCall_4_0() { return cHexColorEStringParserRuleCall_4_0; }
		
		//('outbound' '(' outbound+=[Transition|EString] ( "," outbound+=[Transition|EString])* ')' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'outbound'
		public Keyword getOutboundKeyword_5_0() { return cOutboundKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//outbound+=[Transition|EString]
		public Assignment getOutboundAssignment_5_2() { return cOutboundAssignment_5_2; }
		
		//[Transition|EString]
		public CrossReference getOutboundTransitionCrossReference_5_2_0() { return cOutboundTransitionCrossReference_5_2_0; }
		
		//EString
		public RuleCall getOutboundTransitionEStringParserRuleCall_5_2_0_1() { return cOutboundTransitionEStringParserRuleCall_5_2_0_1; }
		
		//( "," outbound+=[Transition|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//outbound+=[Transition|EString]
		public Assignment getOutboundAssignment_5_3_1() { return cOutboundAssignment_5_3_1; }
		
		//[Transition|EString]
		public CrossReference getOutboundTransitionCrossReference_5_3_1_0() { return cOutboundTransitionCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getOutboundTransitionEStringParserRuleCall_5_3_1_0_1() { return cOutboundTransitionEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//('inbound' '(' inbound+=[Transition|EString] ( "," inbound+=[Transition|EString])* ')' )?
		public Group getGroup_6() { return cGroup_6; }
		
		//'inbound'
		public Keyword getInboundKeyword_6_0() { return cInboundKeyword_6_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_6_1() { return cLeftParenthesisKeyword_6_1; }
		
		//inbound+=[Transition|EString]
		public Assignment getInboundAssignment_6_2() { return cInboundAssignment_6_2; }
		
		//[Transition|EString]
		public CrossReference getInboundTransitionCrossReference_6_2_0() { return cInboundTransitionCrossReference_6_2_0; }
		
		//EString
		public RuleCall getInboundTransitionEStringParserRuleCall_6_2_0_1() { return cInboundTransitionEStringParserRuleCall_6_2_0_1; }
		
		//( "," inbound+=[Transition|EString])*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//inbound+=[Transition|EString]
		public Assignment getInboundAssignment_6_3_1() { return cInboundAssignment_6_3_1; }
		
		//[Transition|EString]
		public CrossReference getInboundTransitionCrossReference_6_3_1_0() { return cInboundTransitionCrossReference_6_3_1_0; }
		
		//EString
		public RuleCall getInboundTransitionEStringParserRuleCall_6_3_1_0_1() { return cInboundTransitionEStringParserRuleCall_6_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6_4() { return cRightParenthesisKeyword_6_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class TransitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bg.bgdsl.BgDsl.Transition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTransitionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cSourceKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cSourceAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cSourceStateCrossReference_5_0 = (CrossReference)cSourceAssignment_5.eContents().get(0);
		private final RuleCall cSourceStateEStringParserRuleCall_5_0_1 = (RuleCall)cSourceStateCrossReference_5_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCommaKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cSourceAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cSourceStateCrossReference_6_1_0 = (CrossReference)cSourceAssignment_6_1.eContents().get(0);
		private final RuleCall cSourceStateEStringParserRuleCall_6_1_0_1 = (RuleCall)cSourceStateCrossReference_6_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cTargetKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cTargetAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final CrossReference cTargetStateCrossReference_9_0 = (CrossReference)cTargetAssignment_9.eContents().get(0);
		private final RuleCall cTargetStateEStringParserRuleCall_9_0_1 = (RuleCall)cTargetStateCrossReference_9_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Transition returns Transition:
		//    'Transition'
		//    name=EString
		//    '{'
		//        'source' '(' source+=[State|EString] ( "," source+=[State|EString])* ')'
		//        'target' target=[State|EString]
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Transition'
		//name=EString
		//'{'
		//    'source' '(' source+=[State|EString] ( "," source+=[State|EString])* ')'
		//    'target' target=[State|EString]
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Transition'
		public Keyword getTransitionKeyword_0() { return cTransitionKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'source'
		public Keyword getSourceKeyword_3() { return cSourceKeyword_3; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4() { return cLeftParenthesisKeyword_4; }
		
		//source+=[State|EString]
		public Assignment getSourceAssignment_5() { return cSourceAssignment_5; }
		
		//[State|EString]
		public CrossReference getSourceStateCrossReference_5_0() { return cSourceStateCrossReference_5_0; }
		
		//EString
		public RuleCall getSourceStateEStringParserRuleCall_5_0_1() { return cSourceStateEStringParserRuleCall_5_0_1; }
		
		//( "," source+=[State|EString])*
		public Group getGroup_6() { return cGroup_6; }
		
		//","
		public Keyword getCommaKeyword_6_0() { return cCommaKeyword_6_0; }
		
		//source+=[State|EString]
		public Assignment getSourceAssignment_6_1() { return cSourceAssignment_6_1; }
		
		//[State|EString]
		public CrossReference getSourceStateCrossReference_6_1_0() { return cSourceStateCrossReference_6_1_0; }
		
		//EString
		public RuleCall getSourceStateEStringParserRuleCall_6_1_0_1() { return cSourceStateEStringParserRuleCall_6_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_7() { return cRightParenthesisKeyword_7; }
		
		//'target'
		public Keyword getTargetKeyword_8() { return cTargetKeyword_8; }
		
		//target=[State|EString]
		public Assignment getTargetAssignment_9() { return cTargetAssignment_9; }
		
		//[State|EString]
		public CrossReference getTargetStateCrossReference_9_0() { return cTargetStateCrossReference_9_0; }
		
		//EString
		public RuleCall getTargetStateEStringParserRuleCall_9_0_1() { return cTargetStateEStringParserRuleCall_9_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}
	public class PatternFilterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bg.bgdsl.BgDsl.PatternFilter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPatternFilterKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cNextFilterKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cNextFilterAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNextFilterFilterParserRuleCall_3_1_0 = (RuleCall)cNextFilterAssignment_3_1.eContents().get(0);
		private final Keyword cPatternsKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cPatternsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cPatternsPatternParserRuleCall_6_0 = (RuleCall)cPatternsAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cPatternsAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cPatternsPatternParserRuleCall_7_1_0 = (RuleCall)cPatternsAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//PatternFilter returns PatternFilter:
		//    'PatternFilter'
		//    name=EString
		//    '{'
		//        ('nextFilter' nextFilter=Filter)?
		//        'patterns' '{' patterns+=Pattern ( "," patterns+=Pattern)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'PatternFilter'
		//name=EString
		//'{'
		//    ('nextFilter' nextFilter=Filter)?
		//    'patterns' '{' patterns+=Pattern ( "," patterns+=Pattern)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'PatternFilter'
		public Keyword getPatternFilterKeyword_0() { return cPatternFilterKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('nextFilter' nextFilter=Filter)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'nextFilter'
		public Keyword getNextFilterKeyword_3_0() { return cNextFilterKeyword_3_0; }
		
		//nextFilter=Filter
		public Assignment getNextFilterAssignment_3_1() { return cNextFilterAssignment_3_1; }
		
		//Filter
		public RuleCall getNextFilterFilterParserRuleCall_3_1_0() { return cNextFilterFilterParserRuleCall_3_1_0; }
		
		//'patterns'
		public Keyword getPatternsKeyword_4() { return cPatternsKeyword_4; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//patterns+=Pattern
		public Assignment getPatternsAssignment_6() { return cPatternsAssignment_6; }
		
		//Pattern
		public RuleCall getPatternsPatternParserRuleCall_6_0() { return cPatternsPatternParserRuleCall_6_0; }
		
		//( "," patterns+=Pattern)*
		public Group getGroup_7() { return cGroup_7; }
		
		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }
		
		//patterns+=Pattern
		public Assignment getPatternsAssignment_7_1() { return cPatternsAssignment_7_1; }
		
		//Pattern
		public RuleCall getPatternsPatternParserRuleCall_7_1_0() { return cPatternsPatternParserRuleCall_7_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class PatternElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bg.bgdsl.BgDsl.Pattern");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPatternKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cStateSelectionKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cStateSelectionAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cStateSelectionStateSelectionEnumRuleCall_3_1_0 = (RuleCall)cStateSelectionAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cMatchStateKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cMatchStateAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cMatchStateStateCrossReference_4_1_0 = (CrossReference)cMatchStateAssignment_4_1.eContents().get(0);
		private final RuleCall cMatchStateStateEStringParserRuleCall_4_1_0_1 = (RuleCall)cMatchStateStateCrossReference_4_1_0.eContents().get(1);
		private final Keyword cRelativecoordinatesKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cRelativecoordinatesAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cRelativecoordinatesRelativeCoordinateParserRuleCall_7_0 = (RuleCall)cRelativecoordinatesAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCommaKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cRelativecoordinatesAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cRelativecoordinatesRelativeCoordinateParserRuleCall_8_1_0 = (RuleCall)cRelativecoordinatesAssignment_8_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Pattern returns Pattern:
		//    'Pattern'
		//    name=EString
		//    '{'
		//        ('stateSelection' stateSelection=StateSelection)?
		//        ('matchState' matchState=[State|EString])?
		//        'relativecoordinates' '{' relativecoordinates+=RelativeCoordinate ( "," relativecoordinates+=RelativeCoordinate)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Pattern'
		//name=EString
		//'{'
		//    ('stateSelection' stateSelection=StateSelection)?
		//    ('matchState' matchState=[State|EString])?
		//    'relativecoordinates' '{' relativecoordinates+=RelativeCoordinate ( "," relativecoordinates+=RelativeCoordinate)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Pattern'
		public Keyword getPatternKeyword_0() { return cPatternKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('stateSelection' stateSelection=StateSelection)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'stateSelection'
		public Keyword getStateSelectionKeyword_3_0() { return cStateSelectionKeyword_3_0; }
		
		//stateSelection=StateSelection
		public Assignment getStateSelectionAssignment_3_1() { return cStateSelectionAssignment_3_1; }
		
		//StateSelection
		public RuleCall getStateSelectionStateSelectionEnumRuleCall_3_1_0() { return cStateSelectionStateSelectionEnumRuleCall_3_1_0; }
		
		//('matchState' matchState=[State|EString])?
		public Group getGroup_4() { return cGroup_4; }
		
		//'matchState'
		public Keyword getMatchStateKeyword_4_0() { return cMatchStateKeyword_4_0; }
		
		//matchState=[State|EString]
		public Assignment getMatchStateAssignment_4_1() { return cMatchStateAssignment_4_1; }
		
		//[State|EString]
		public CrossReference getMatchStateStateCrossReference_4_1_0() { return cMatchStateStateCrossReference_4_1_0; }
		
		//EString
		public RuleCall getMatchStateStateEStringParserRuleCall_4_1_0_1() { return cMatchStateStateEStringParserRuleCall_4_1_0_1; }
		
		//'relativecoordinates'
		public Keyword getRelativecoordinatesKeyword_5() { return cRelativecoordinatesKeyword_5; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6() { return cLeftCurlyBracketKeyword_6; }
		
		//relativecoordinates+=RelativeCoordinate
		public Assignment getRelativecoordinatesAssignment_7() { return cRelativecoordinatesAssignment_7; }
		
		//RelativeCoordinate
		public RuleCall getRelativecoordinatesRelativeCoordinateParserRuleCall_7_0() { return cRelativecoordinatesRelativeCoordinateParserRuleCall_7_0; }
		
		//( "," relativecoordinates+=RelativeCoordinate)*
		public Group getGroup_8() { return cGroup_8; }
		
		//","
		public Keyword getCommaKeyword_8_0() { return cCommaKeyword_8_0; }
		
		//relativecoordinates+=RelativeCoordinate
		public Assignment getRelativecoordinatesAssignment_8_1() { return cRelativecoordinatesAssignment_8_1; }
		
		//RelativeCoordinate
		public RuleCall getRelativecoordinatesRelativeCoordinateParserRuleCall_8_1_0() { return cRelativecoordinatesRelativeCoordinateParserRuleCall_8_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}
	public class RelativeCoordinateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bg.bgdsl.BgDsl.RelativeCoordinate");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRelativeCoordinateKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cXKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cXAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cXEIntParserRuleCall_3_0 = (RuleCall)cXAssignment_3.eContents().get(0);
		private final Keyword cYKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cYAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cYEIntParserRuleCall_5_0 = (RuleCall)cYAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//RelativeCoordinate returns RelativeCoordinate:
		//    'RelativeCoordinate'
		//    '{'
		//        'x' x=EInt
		//        'y' y=EInt
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'RelativeCoordinate'
		//'{'
		//    'x' x=EInt
		//    'y' y=EInt
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'RelativeCoordinate'
		public Keyword getRelativeCoordinateKeyword_0() { return cRelativeCoordinateKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'x'
		public Keyword getXKeyword_2() { return cXKeyword_2; }
		
		//x=EInt
		public Assignment getXAssignment_3() { return cXAssignment_3; }
		
		//EInt
		public RuleCall getXEIntParserRuleCall_3_0() { return cXEIntParserRuleCall_3_0; }
		
		//'y'
		public Keyword getYKeyword_4() { return cYKeyword_4; }
		
		//y=EInt
		public Assignment getYAssignment_5() { return cYAssignment_5; }
		
		//EInt
		public RuleCall getYEIntParserRuleCall_5_0() { return cYEIntParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	
	public class StateSelectionElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bg.bgdsl.BgDsl.StateSelection");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cCurrentPlayerEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cCurrentPlayerCurrentPlayerKeyword_0_0 = (Keyword)cCurrentPlayerEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cOtherPlayerEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cOtherPlayerOtherPlayerKeyword_1_0 = (Keyword)cOtherPlayerEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cStateBasedEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cStateBasedStateBasedKeyword_2_0 = (Keyword)cStateBasedEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum StateSelection returns StateSelection:
		//                CurrentPlayer = 'CurrentPlayer' | OtherPlayer = 'OtherPlayer' | StateBased = 'StateBased';
		public EnumRule getRule() { return rule; }
		
		//CurrentPlayer = 'CurrentPlayer' | OtherPlayer = 'OtherPlayer' | StateBased = 'StateBased'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//CurrentPlayer = 'CurrentPlayer'
		public EnumLiteralDeclaration getCurrentPlayerEnumLiteralDeclaration_0() { return cCurrentPlayerEnumLiteralDeclaration_0; }
		
		//'CurrentPlayer'
		public Keyword getCurrentPlayerCurrentPlayerKeyword_0_0() { return cCurrentPlayerCurrentPlayerKeyword_0_0; }
		
		//OtherPlayer = 'OtherPlayer'
		public EnumLiteralDeclaration getOtherPlayerEnumLiteralDeclaration_1() { return cOtherPlayerEnumLiteralDeclaration_1; }
		
		//'OtherPlayer'
		public Keyword getOtherPlayerOtherPlayerKeyword_1_0() { return cOtherPlayerOtherPlayerKeyword_1_0; }
		
		//StateBased = 'StateBased'
		public EnumLiteralDeclaration getStateBasedEnumLiteralDeclaration_2() { return cStateBasedEnumLiteralDeclaration_2; }
		
		//'StateBased'
		public Keyword getStateBasedStateBasedKeyword_2_0() { return cStateBasedStateBasedKeyword_2_0; }
	}
	public class TurnTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bg.bgdsl.BgDsl.TurnType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cTurnBasedEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cTurnBasedTurnBasedKeyword_0_0 = (Keyword)cTurnBasedEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cSimultaneousEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cSimultaneousSimultaneousKeyword_1_0 = (Keyword)cSimultaneousEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum TurnType returns TurnType:
		//                TurnBased = 'TurnBased' | Simultaneous = 'Simultaneous';
		public EnumRule getRule() { return rule; }
		
		//TurnBased = 'TurnBased' | Simultaneous = 'Simultaneous'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//TurnBased = 'TurnBased'
		public EnumLiteralDeclaration getTurnBasedEnumLiteralDeclaration_0() { return cTurnBasedEnumLiteralDeclaration_0; }
		
		//'TurnBased'
		public Keyword getTurnBasedTurnBasedKeyword_0_0() { return cTurnBasedTurnBasedKeyword_0_0; }
		
		//Simultaneous = 'Simultaneous'
		public EnumLiteralDeclaration getSimultaneousEnumLiteralDeclaration_1() { return cSimultaneousEnumLiteralDeclaration_1; }
		
		//'Simultaneous'
		public Keyword getSimultaneousSimultaneousKeyword_1_0() { return cSimultaneousSimultaneousKeyword_1_0; }
	}
	
	private final GameElements pGame;
	private final FilterElements pFilter;
	private final BoardElements pBoard;
	private final EStringElements pEString;
	private final PlayerElements pPlayer;
	private final EIntElements pEInt;
	private final TileElements pTile;
	private final LegalMovesPipelineElements pLegalMovesPipeline;
	private final EffectPipelineElements pEffectPipeline;
	private final EBooleanElements pEBoolean;
	private final TilePlacementElements pTilePlacement;
	private final StateElements pState;
	private final TransitionElements pTransition;
	private final PatternFilterElements pPatternFilter;
	private final PatternElements pPattern;
	private final RelativeCoordinateElements pRelativeCoordinate;
	private final StateSelectionElements eStateSelection;
	private final TurnTypeElements eTurnType;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public BgDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pGame = new GameElements();
		this.pFilter = new FilterElements();
		this.pBoard = new BoardElements();
		this.pEString = new EStringElements();
		this.pPlayer = new PlayerElements();
		this.pEInt = new EIntElements();
		this.pTile = new TileElements();
		this.pLegalMovesPipeline = new LegalMovesPipelineElements();
		this.pEffectPipeline = new EffectPipelineElements();
		this.pEBoolean = new EBooleanElements();
		this.pTilePlacement = new TilePlacementElements();
		this.pState = new StateElements();
		this.pTransition = new TransitionElements();
		this.pPatternFilter = new PatternFilterElements();
		this.pPattern = new PatternElements();
		this.pRelativeCoordinate = new RelativeCoordinateElements();
		this.eStateSelection = new StateSelectionElements();
		this.eTurnType = new TurnTypeElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("no.ntnu.tdt4250.bg.bgdsl.BgDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Game returns Game:
	//    'Game'
	//    name=EString
	//    '{'
	//        ('initialPlayer' initialPlayer=[Player|EString])?
	//        'board' board=Board
	//        ('players' '{' players+=Player ( "," players+=Player)* '}' )?
	//        'turnPolicy' turnPolicy=TurnType
	//    '}';
	public GameElements getGameAccess() {
		return pGame;
	}
	
	public ParserRule getGameRule() {
		return getGameAccess().getRule();
	}
	
	//Filter returns Filter:
	//    PatternFilter;
	public FilterElements getFilterAccess() {
		return pFilter;
	}
	
	public ParserRule getFilterRule() {
		return getFilterAccess().getRule();
	}
	
	//Board returns Board:
	//    checkered?='checkered'
	//    'Board'
	//    '{'
	//        'width' width=EInt
	//        'height' height=EInt
	//        'tiles' '{' tiles+=Tile ( "," tiles+=Tile)* '}'
	//        ('legalMovesPipeline' legalMovesPipeline=LegalMovesPipeline)?
	//        ('effectPipeline'effectPipeline=EffectPipeline)?
	//        'tileplacement' '{' tileplacement+=TilePlacement ( "," tileplacement+=TilePlacement)* '}'
	//    '}';
	public BoardElements getBoardAccess() {
		return pBoard;
	}
	
	public ParserRule getBoardRule() {
		return getBoardAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Player returns Player:
	//    'Player'
	//    name=EString
	//    '{'
	//        'hexColor' hexColor=EString
	//        'associatedState' associatedState=[State|EString]
	//    '}';
	public PlayerElements getPlayerAccess() {
		return pPlayer;
	}
	
	public ParserRule getPlayerRule() {
		return getPlayerAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    '-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//Tile returns Tile:
	//    'Tile'
	//    type=EString
	//    '{'
	//        'hexColor' hexColor=EString
	//        'name' name=EString
	//        'states' '{' states+=State ( "," states+=State)* '}'
	//        ('transitions' '{' transitions+=Transition ( "," transitions+=Transition)* '}' )?
	//        'initialState' initialState=State
	//    '}';
	public TileElements getTileAccess() {
		return pTile;
	}
	
	public ParserRule getTileRule() {
		return getTileAccess().getRule();
	}
	
	//LegalMovesPipeline returns LegalMovesPipeline:
	//    {LegalMovesPipeline}
	//    'LegalMovesPipeline'
	//    '{'
	//        ('filter' filter=Filter)?
	//    '}';
	public LegalMovesPipelineElements getLegalMovesPipelineAccess() {
		return pLegalMovesPipeline;
	}
	
	public ParserRule getLegalMovesPipelineRule() {
		return getLegalMovesPipelineAccess().getRule();
	}
	
	//EffectPipeline returns EffectPipeline:
	//    {EffectPipeline}
	//    'EffectPipeline'
	//    '{'
	//        ('filter' filter=Filter)?
	//    '}';
	public EffectPipelineElements getEffectPipelineAccess() {
		return pEffectPipeline;
	}
	
	public ParserRule getEffectPipelineRule() {
		return getEffectPipelineAccess().getRule();
	}
	
	//EBoolean returns ecore::EBoolean:
	//    'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//TilePlacement returns TilePlacement:
	//    'TilePlacement'
	//    '{'
	//        'row' row=EInt
	//        'column' column=EInt
	//        'tile' tile=[Tile|EString]
	//    '}';
	public TilePlacementElements getTilePlacementAccess() {
		return pTilePlacement;
	}
	
	public ParserRule getTilePlacementRule() {
		return getTilePlacementAccess().getRule();
	}
	
	//State returns State:
	//    'State'
	//    name=EString
	//    '{'
	//        'hexColor' hexColor=EString
	//        ('outbound' '(' outbound+=[Transition|EString] ( "," outbound+=[Transition|EString])* ')' )?
	//        ('inbound' '(' inbound+=[Transition|EString] ( "," inbound+=[Transition|EString])* ')' )?
	//    '}';
	public StateElements getStateAccess() {
		return pState;
	}
	
	public ParserRule getStateRule() {
		return getStateAccess().getRule();
	}
	
	//Transition returns Transition:
	//    'Transition'
	//    name=EString
	//    '{'
	//        'source' '(' source+=[State|EString] ( "," source+=[State|EString])* ')'
	//        'target' target=[State|EString]
	//    '}';
	public TransitionElements getTransitionAccess() {
		return pTransition;
	}
	
	public ParserRule getTransitionRule() {
		return getTransitionAccess().getRule();
	}
	
	//PatternFilter returns PatternFilter:
	//    'PatternFilter'
	//    name=EString
	//    '{'
	//        ('nextFilter' nextFilter=Filter)?
	//        'patterns' '{' patterns+=Pattern ( "," patterns+=Pattern)* '}'
	//    '}';
	public PatternFilterElements getPatternFilterAccess() {
		return pPatternFilter;
	}
	
	public ParserRule getPatternFilterRule() {
		return getPatternFilterAccess().getRule();
	}
	
	//Pattern returns Pattern:
	//    'Pattern'
	//    name=EString
	//    '{'
	//        ('stateSelection' stateSelection=StateSelection)?
	//        ('matchState' matchState=[State|EString])?
	//        'relativecoordinates' '{' relativecoordinates+=RelativeCoordinate ( "," relativecoordinates+=RelativeCoordinate)* '}'
	//    '}';
	public PatternElements getPatternAccess() {
		return pPattern;
	}
	
	public ParserRule getPatternRule() {
		return getPatternAccess().getRule();
	}
	
	//RelativeCoordinate returns RelativeCoordinate:
	//    'RelativeCoordinate'
	//    '{'
	//        'x' x=EInt
	//        'y' y=EInt
	//    '}';
	public RelativeCoordinateElements getRelativeCoordinateAccess() {
		return pRelativeCoordinate;
	}
	
	public ParserRule getRelativeCoordinateRule() {
		return getRelativeCoordinateAccess().getRule();
	}
	
	//enum StateSelection returns StateSelection:
	//                CurrentPlayer = 'CurrentPlayer' | OtherPlayer = 'OtherPlayer' | StateBased = 'StateBased';
	public StateSelectionElements getStateSelectionAccess() {
		return eStateSelection;
	}
	
	public EnumRule getStateSelectionRule() {
		return getStateSelectionAccess().getRule();
	}
	
	//enum TurnType returns TurnType:
	//                TurnBased = 'TurnBased' | Simultaneous = 'Simultaneous';
	public TurnTypeElements getTurnTypeAccess() {
		return eTurnType;
	}
	
	public EnumRule getTurnTypeRule() {
		return getTurnTypeAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
