/*
 * generated by Xtext 2.39.0
 */
package no.ntnu.tdt4250.bg.bgdsl.ui;

import com.google.inject.Injector;
import no.ntnu.tdt4250.bg.bgdsl.ui.internal.BgdslActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BgDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(BgdslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		BgdslActivator activator = BgdslActivator.getInstance();
		return activator != null ? activator.getInjector(BgdslActivator.NO_NTNU_TDT4250_BG_BGDSL_BGDSL) : null;
	}

}
