/*
 * generated by Xtext 2.39.0
 */
package no.ntnu.tdt4250.bgdsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class BgDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class PlayerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bgdsl.BgDsl.Player");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPlayerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Player returns bg::Player:
		//    'Player' name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//'Player' name=EString
		public Group getGroup() { return cGroup; }
		
		//'Player'
		public Keyword getPlayerKeyword_0() { return cPlayerKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
	}
	public class TurnPolicyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bgdsl.BgDsl.TurnPolicy");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTurnPolicyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cTypeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTypeTurnTypeEnumRuleCall_3_0 = (RuleCall)cTypeAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//TurnPolicy returns bg::TurnPolicy:
		//    'TurnPolicy'
		//    '{'
		//        'type' type=TurnType
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'TurnPolicy'
		//'{'
		//    'type' type=TurnType
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'TurnPolicy'
		public Keyword getTurnPolicyKeyword_0() { return cTurnPolicyKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'type'
		public Keyword getTypeKeyword_2() { return cTypeKeyword_2; }
		
		//type=TurnType
		public Assignment getTypeAssignment_3() { return cTypeAssignment_3; }
		
		//TurnType
		public RuleCall getTypeTurnTypeEnumRuleCall_3_0() { return cTypeTurnTypeEnumRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class GameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bgdsl.BgDsl.Game");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGameKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cBoardKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cBoardAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cBoardBoardParserRuleCall_4_0 = (RuleCall)cBoardAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cPlayersKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cPlayersAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cPlayersPlayerParserRuleCall_5_2_0 = (RuleCall)cPlayersAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cPlayersAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cPlayersPlayerParserRuleCall_5_3_1_0 = (RuleCall)cPlayersAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cTurnPolicyKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cTurnPolicyAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cTurnPolicyTurnPolicyParserRuleCall_6_2_0 = (RuleCall)cTurnPolicyAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cTurnPolicyAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cTurnPolicyTurnPolicyParserRuleCall_6_3_1_0 = (RuleCall)cTurnPolicyAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cInitialPlayerKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cInitialPlayerAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final CrossReference cInitialPlayerPlayerCrossReference_7_1_0 = (CrossReference)cInitialPlayerAssignment_7_1.eContents().get(0);
		private final RuleCall cInitialPlayerPlayerEStringParserRuleCall_7_1_0_1 = (RuleCall)cInitialPlayerPlayerCrossReference_7_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Game returns bg::Game:
		//    'Game' name=EString
		//    '{'
		//        'board' board=Board
		//        ('players' '{' players+=Player (',' players+=Player)* '}')?
		//        ('turnPolicy' '{' turnPolicy+=TurnPolicy (',' turnPolicy+=TurnPolicy)* '}')?
		//        ('initialPlayer' initialPlayer=[bg::Player|EString])?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Game' name=EString
		//'{'
		//    'board' board=Board
		//    ('players' '{' players+=Player (',' players+=Player)* '}')?
		//    ('turnPolicy' '{' turnPolicy+=TurnPolicy (',' turnPolicy+=TurnPolicy)* '}')?
		//    ('initialPlayer' initialPlayer=[bg::Player|EString])?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Game'
		public Keyword getGameKeyword_0() { return cGameKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'board'
		public Keyword getBoardKeyword_3() { return cBoardKeyword_3; }
		
		//board=Board
		public Assignment getBoardAssignment_4() { return cBoardAssignment_4; }
		
		//Board
		public RuleCall getBoardBoardParserRuleCall_4_0() { return cBoardBoardParserRuleCall_4_0; }
		
		//('players' '{' players+=Player (',' players+=Player)* '}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'players'
		public Keyword getPlayersKeyword_5_0() { return cPlayersKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//players+=Player
		public Assignment getPlayersAssignment_5_2() { return cPlayersAssignment_5_2; }
		
		//Player
		public RuleCall getPlayersPlayerParserRuleCall_5_2_0() { return cPlayersPlayerParserRuleCall_5_2_0; }
		
		//(',' players+=Player)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//','
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//players+=Player
		public Assignment getPlayersAssignment_5_3_1() { return cPlayersAssignment_5_3_1; }
		
		//Player
		public RuleCall getPlayersPlayerParserRuleCall_5_3_1_0() { return cPlayersPlayerParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//('turnPolicy' '{' turnPolicy+=TurnPolicy (',' turnPolicy+=TurnPolicy)* '}')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'turnPolicy'
		public Keyword getTurnPolicyKeyword_6_0() { return cTurnPolicyKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//turnPolicy+=TurnPolicy
		public Assignment getTurnPolicyAssignment_6_2() { return cTurnPolicyAssignment_6_2; }
		
		//TurnPolicy
		public RuleCall getTurnPolicyTurnPolicyParserRuleCall_6_2_0() { return cTurnPolicyTurnPolicyParserRuleCall_6_2_0; }
		
		//(',' turnPolicy+=TurnPolicy)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//','
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//turnPolicy+=TurnPolicy
		public Assignment getTurnPolicyAssignment_6_3_1() { return cTurnPolicyAssignment_6_3_1; }
		
		//TurnPolicy
		public RuleCall getTurnPolicyTurnPolicyParserRuleCall_6_3_1_0() { return cTurnPolicyTurnPolicyParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//('initialPlayer' initialPlayer=[bg::Player|EString])?
		public Group getGroup_7() { return cGroup_7; }
		
		//'initialPlayer'
		public Keyword getInitialPlayerKeyword_7_0() { return cInitialPlayerKeyword_7_0; }
		
		//initialPlayer=[bg::Player|EString]
		public Assignment getInitialPlayerAssignment_7_1() { return cInitialPlayerAssignment_7_1; }
		
		//[bg::Player|EString]
		public CrossReference getInitialPlayerPlayerCrossReference_7_1_0() { return cInitialPlayerPlayerCrossReference_7_1_0; }
		
		//EString
		public RuleCall getInitialPlayerPlayerEStringParserRuleCall_7_1_0_1() { return cInitialPlayerPlayerEStringParserRuleCall_7_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class BoardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bgdsl.BgDsl.Board");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cCheckeredAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cCheckeredCheckeredKeyword_0_0 = (Keyword)cCheckeredAssignment_0.eContents().get(0);
		private final Keyword cBoardKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cWidthKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cWidthAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cWidthEIntParserRuleCall_4_0 = (RuleCall)cWidthAssignment_4.eContents().get(0);
		private final Keyword cHeightKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cHeightAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cHeightEIntParserRuleCall_6_0 = (RuleCall)cHeightAssignment_6.eContents().get(0);
		private final Keyword cTilesKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cLeftCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cTilesAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cTilesTileParserRuleCall_9_0 = (RuleCall)cTilesAssignment_9.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cCommaKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cTilesAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cTilesTileParserRuleCall_10_1_0 = (RuleCall)cTilesAssignment_10_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cLegalMovesPipelineKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_12_1 = (Keyword)cGroup_12.eContents().get(1);
		private final Assignment cLegalMovesPipelineAssignment_12_2 = (Assignment)cGroup_12.eContents().get(2);
		private final RuleCall cLegalMovesPipelineLegalMovesPipelineParserRuleCall_12_2_0 = (RuleCall)cLegalMovesPipelineAssignment_12_2.eContents().get(0);
		private final Group cGroup_12_3 = (Group)cGroup_12.eContents().get(3);
		private final Keyword cCommaKeyword_12_3_0 = (Keyword)cGroup_12_3.eContents().get(0);
		private final Assignment cLegalMovesPipelineAssignment_12_3_1 = (Assignment)cGroup_12_3.eContents().get(1);
		private final RuleCall cLegalMovesPipelineLegalMovesPipelineParserRuleCall_12_3_1_0 = (RuleCall)cLegalMovesPipelineAssignment_12_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12_4 = (Keyword)cGroup_12.eContents().get(4);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Keyword cEffectPipelineKeyword_13_0 = (Keyword)cGroup_13.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_13_1 = (Keyword)cGroup_13.eContents().get(1);
		private final Assignment cEffectPipelineAssignment_13_2 = (Assignment)cGroup_13.eContents().get(2);
		private final RuleCall cEffectPipelineEffectPipelineParserRuleCall_13_2_0 = (RuleCall)cEffectPipelineAssignment_13_2.eContents().get(0);
		private final Group cGroup_13_3 = (Group)cGroup_13.eContents().get(3);
		private final Keyword cCommaKeyword_13_3_0 = (Keyword)cGroup_13_3.eContents().get(0);
		private final Assignment cEffectPipelineAssignment_13_3_1 = (Assignment)cGroup_13_3.eContents().get(1);
		private final RuleCall cEffectPipelineEffectPipelineParserRuleCall_13_3_1_0 = (RuleCall)cEffectPipelineAssignment_13_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13_4 = (Keyword)cGroup_13.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		
		//Board returns bg::Board:
		//    checkered?='checkered'
		//    'Board'
		//    '{'
		//        'width' width=EInt
		//        'height' height=EInt
		//        'tiles' '{' tiles+=Tile ( "," tiles+=Tile)* '}'
		//        ('legalMovesPipeline' '{' legalMovesPipeline+=LegalMovesPipeline ( "," legalMovesPipeline+=LegalMovesPipeline)* '}' )?
		//        ('effectPipeline' '{' effectPipeline+=EffectPipeline ( "," effectPipeline+=EffectPipeline)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//checkered?='checkered'
		//'Board'
		//'{'
		//    'width' width=EInt
		//    'height' height=EInt
		//    'tiles' '{' tiles+=Tile ( "," tiles+=Tile)* '}'
		//    ('legalMovesPipeline' '{' legalMovesPipeline+=LegalMovesPipeline ( "," legalMovesPipeline+=LegalMovesPipeline)* '}' )?
		//    ('effectPipeline' '{' effectPipeline+=EffectPipeline ( "," effectPipeline+=EffectPipeline)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//checkered?='checkered'
		public Assignment getCheckeredAssignment_0() { return cCheckeredAssignment_0; }
		
		//'checkered'
		public Keyword getCheckeredCheckeredKeyword_0_0() { return cCheckeredCheckeredKeyword_0_0; }
		
		//'Board'
		public Keyword getBoardKeyword_1() { return cBoardKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'width'
		public Keyword getWidthKeyword_3() { return cWidthKeyword_3; }
		
		//width=EInt
		public Assignment getWidthAssignment_4() { return cWidthAssignment_4; }
		
		//EInt
		public RuleCall getWidthEIntParserRuleCall_4_0() { return cWidthEIntParserRuleCall_4_0; }
		
		//'height'
		public Keyword getHeightKeyword_5() { return cHeightKeyword_5; }
		
		//height=EInt
		public Assignment getHeightAssignment_6() { return cHeightAssignment_6; }
		
		//EInt
		public RuleCall getHeightEIntParserRuleCall_6_0() { return cHeightEIntParserRuleCall_6_0; }
		
		//'tiles'
		public Keyword getTilesKeyword_7() { return cTilesKeyword_7; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_8() { return cLeftCurlyBracketKeyword_8; }
		
		//tiles+=Tile
		public Assignment getTilesAssignment_9() { return cTilesAssignment_9; }
		
		//Tile
		public RuleCall getTilesTileParserRuleCall_9_0() { return cTilesTileParserRuleCall_9_0; }
		
		//( "," tiles+=Tile)*
		public Group getGroup_10() { return cGroup_10; }
		
		//","
		public Keyword getCommaKeyword_10_0() { return cCommaKeyword_10_0; }
		
		//tiles+=Tile
		public Assignment getTilesAssignment_10_1() { return cTilesAssignment_10_1; }
		
		//Tile
		public RuleCall getTilesTileParserRuleCall_10_1_0() { return cTilesTileParserRuleCall_10_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
		
		//('legalMovesPipeline' '{' legalMovesPipeline+=LegalMovesPipeline ( "," legalMovesPipeline+=LegalMovesPipeline)* '}' )?
		public Group getGroup_12() { return cGroup_12; }
		
		//'legalMovesPipeline'
		public Keyword getLegalMovesPipelineKeyword_12_0() { return cLegalMovesPipelineKeyword_12_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_12_1() { return cLeftCurlyBracketKeyword_12_1; }
		
		//legalMovesPipeline+=LegalMovesPipeline
		public Assignment getLegalMovesPipelineAssignment_12_2() { return cLegalMovesPipelineAssignment_12_2; }
		
		//LegalMovesPipeline
		public RuleCall getLegalMovesPipelineLegalMovesPipelineParserRuleCall_12_2_0() { return cLegalMovesPipelineLegalMovesPipelineParserRuleCall_12_2_0; }
		
		//( "," legalMovesPipeline+=LegalMovesPipeline)*
		public Group getGroup_12_3() { return cGroup_12_3; }
		
		//","
		public Keyword getCommaKeyword_12_3_0() { return cCommaKeyword_12_3_0; }
		
		//legalMovesPipeline+=LegalMovesPipeline
		public Assignment getLegalMovesPipelineAssignment_12_3_1() { return cLegalMovesPipelineAssignment_12_3_1; }
		
		//LegalMovesPipeline
		public RuleCall getLegalMovesPipelineLegalMovesPipelineParserRuleCall_12_3_1_0() { return cLegalMovesPipelineLegalMovesPipelineParserRuleCall_12_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12_4() { return cRightCurlyBracketKeyword_12_4; }
		
		//('effectPipeline' '{' effectPipeline+=EffectPipeline ( "," effectPipeline+=EffectPipeline)* '}' )?
		public Group getGroup_13() { return cGroup_13; }
		
		//'effectPipeline'
		public Keyword getEffectPipelineKeyword_13_0() { return cEffectPipelineKeyword_13_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_13_1() { return cLeftCurlyBracketKeyword_13_1; }
		
		//effectPipeline+=EffectPipeline
		public Assignment getEffectPipelineAssignment_13_2() { return cEffectPipelineAssignment_13_2; }
		
		//EffectPipeline
		public RuleCall getEffectPipelineEffectPipelineParserRuleCall_13_2_0() { return cEffectPipelineEffectPipelineParserRuleCall_13_2_0; }
		
		//( "," effectPipeline+=EffectPipeline)*
		public Group getGroup_13_3() { return cGroup_13_3; }
		
		//","
		public Keyword getCommaKeyword_13_3_0() { return cCommaKeyword_13_3_0; }
		
		//effectPipeline+=EffectPipeline
		public Assignment getEffectPipelineAssignment_13_3_1() { return cEffectPipelineAssignment_13_3_1; }
		
		//EffectPipeline
		public RuleCall getEffectPipelineEffectPipelineParserRuleCall_13_3_1_0() { return cEffectPipelineEffectPipelineParserRuleCall_13_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_13_4() { return cRightCurlyBracketKeyword_13_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
	}
	public class FilterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bgdsl.BgDsl.Filter");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSomeFilter1ParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSomeFilter2ParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Filter returns bg::Filter:
		//    SomeFilter1 | SomeFilter2;
		@Override public ParserRule getRule() { return rule; }
		
		//SomeFilter1 | SomeFilter2
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//SomeFilter1
		public RuleCall getSomeFilter1ParserRuleCall_0() { return cSomeFilter1ParserRuleCall_0; }
		
		//SomeFilter2
		public RuleCall getSomeFilter2ParserRuleCall_1() { return cSomeFilter2ParserRuleCall_1; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bgdsl.BgDsl.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class TileElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bgdsl.BgDsl.Tile");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTileKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cRowKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cRowAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cRowEIntParserRuleCall_3_0 = (RuleCall)cRowAssignment_3.eContents().get(0);
		private final Keyword cColKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cColAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cColEIntParserRuleCall_5_0 = (RuleCall)cColAssignment_5.eContents().get(0);
		private final Keyword cColorKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cColorAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cColorEStringParserRuleCall_7_0 = (RuleCall)cColorAssignment_7.eContents().get(0);
		private final Keyword cStatesKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cLeftCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cStatesAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cStatesStateParserRuleCall_10_0 = (RuleCall)cStatesAssignment_10.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cCommaKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cStatesAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall cStatesStateParserRuleCall_11_1_0 = (RuleCall)cStatesAssignment_11_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Keyword cTransitionsKeyword_13_0 = (Keyword)cGroup_13.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_13_1 = (Keyword)cGroup_13.eContents().get(1);
		private final Assignment cTransitionsAssignment_13_2 = (Assignment)cGroup_13.eContents().get(2);
		private final RuleCall cTransitionsTransitionParserRuleCall_13_2_0 = (RuleCall)cTransitionsAssignment_13_2.eContents().get(0);
		private final Group cGroup_13_3 = (Group)cGroup_13.eContents().get(3);
		private final Keyword cCommaKeyword_13_3_0 = (Keyword)cGroup_13_3.eContents().get(0);
		private final Assignment cTransitionsAssignment_13_3_1 = (Assignment)cGroup_13_3.eContents().get(1);
		private final RuleCall cTransitionsTransitionParserRuleCall_13_3_1_0 = (RuleCall)cTransitionsAssignment_13_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13_4 = (Keyword)cGroup_13.eContents().get(4);
		private final Keyword cInitialStateKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Assignment cInitialStateAssignment_15 = (Assignment)cGroup.eContents().get(15);
		private final RuleCall cInitialStateStateParserRuleCall_15_0 = (RuleCall)cInitialStateAssignment_15.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_16 = (Keyword)cGroup.eContents().get(16);
		
		//Tile returns bg::Tile:
		//    'Tile'
		//    '{'
		//        'row' row=EInt
		//        'col' col=EInt
		//        'color' color=EString
		//        'states' '{' states+=State ( "," states+=State)* '}'
		//        ('transitions' '{' transitions+=Transition ( "," transitions+=Transition)* '}' )?
		//        'initialState' initialState=State
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Tile'
		//'{'
		//    'row' row=EInt
		//    'col' col=EInt
		//    'color' color=EString
		//    'states' '{' states+=State ( "," states+=State)* '}'
		//    ('transitions' '{' transitions+=Transition ( "," transitions+=Transition)* '}' )?
		//    'initialState' initialState=State
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Tile'
		public Keyword getTileKeyword_0() { return cTileKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'row'
		public Keyword getRowKeyword_2() { return cRowKeyword_2; }
		
		//row=EInt
		public Assignment getRowAssignment_3() { return cRowAssignment_3; }
		
		//EInt
		public RuleCall getRowEIntParserRuleCall_3_0() { return cRowEIntParserRuleCall_3_0; }
		
		//'col'
		public Keyword getColKeyword_4() { return cColKeyword_4; }
		
		//col=EInt
		public Assignment getColAssignment_5() { return cColAssignment_5; }
		
		//EInt
		public RuleCall getColEIntParserRuleCall_5_0() { return cColEIntParserRuleCall_5_0; }
		
		//'color'
		public Keyword getColorKeyword_6() { return cColorKeyword_6; }
		
		//color=EString
		public Assignment getColorAssignment_7() { return cColorAssignment_7; }
		
		//EString
		public RuleCall getColorEStringParserRuleCall_7_0() { return cColorEStringParserRuleCall_7_0; }
		
		//'states'
		public Keyword getStatesKeyword_8() { return cStatesKeyword_8; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_9() { return cLeftCurlyBracketKeyword_9; }
		
		//states+=State
		public Assignment getStatesAssignment_10() { return cStatesAssignment_10; }
		
		//State
		public RuleCall getStatesStateParserRuleCall_10_0() { return cStatesStateParserRuleCall_10_0; }
		
		//( "," states+=State)*
		public Group getGroup_11() { return cGroup_11; }
		
		//","
		public Keyword getCommaKeyword_11_0() { return cCommaKeyword_11_0; }
		
		//states+=State
		public Assignment getStatesAssignment_11_1() { return cStatesAssignment_11_1; }
		
		//State
		public RuleCall getStatesStateParserRuleCall_11_1_0() { return cStatesStateParserRuleCall_11_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
		
		//('transitions' '{' transitions+=Transition ( "," transitions+=Transition)* '}' )?
		public Group getGroup_13() { return cGroup_13; }
		
		//'transitions'
		public Keyword getTransitionsKeyword_13_0() { return cTransitionsKeyword_13_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_13_1() { return cLeftCurlyBracketKeyword_13_1; }
		
		//transitions+=Transition
		public Assignment getTransitionsAssignment_13_2() { return cTransitionsAssignment_13_2; }
		
		//Transition
		public RuleCall getTransitionsTransitionParserRuleCall_13_2_0() { return cTransitionsTransitionParserRuleCall_13_2_0; }
		
		//( "," transitions+=Transition)*
		public Group getGroup_13_3() { return cGroup_13_3; }
		
		//","
		public Keyword getCommaKeyword_13_3_0() { return cCommaKeyword_13_3_0; }
		
		//transitions+=Transition
		public Assignment getTransitionsAssignment_13_3_1() { return cTransitionsAssignment_13_3_1; }
		
		//Transition
		public RuleCall getTransitionsTransitionParserRuleCall_13_3_1_0() { return cTransitionsTransitionParserRuleCall_13_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_13_4() { return cRightCurlyBracketKeyword_13_4; }
		
		//'initialState'
		public Keyword getInitialStateKeyword_14() { return cInitialStateKeyword_14; }
		
		//initialState=State
		public Assignment getInitialStateAssignment_15() { return cInitialStateAssignment_15; }
		
		//State
		public RuleCall getInitialStateStateParserRuleCall_15_0() { return cInitialStateStateParserRuleCall_15_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_16() { return cRightCurlyBracketKeyword_16; }
	}
	public class LegalMovesPipelineElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bgdsl.BgDsl.LegalMovesPipeline");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cLegalMovesPipelineAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLegalMovesPipelineKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cFilterKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cFilterAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cFilterFilterCrossReference_3_1_0 = (CrossReference)cFilterAssignment_3_1.eContents().get(0);
		private final RuleCall cFilterFilterEStringParserRuleCall_3_1_0_1 = (RuleCall)cFilterFilterCrossReference_3_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//LegalMovesPipeline returns bg::LegalMovesPipeline:
		//    {bg::LegalMovesPipeline}
		//    'LegalMovesPipeline'
		//    '{'
		//        ('filter' filter=[bg::Filter|EString])?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{bg::LegalMovesPipeline}
		//'LegalMovesPipeline'
		//'{'
		//    ('filter' filter=[bg::Filter|EString])?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{bg::LegalMovesPipeline}
		public Action getLegalMovesPipelineAction_0() { return cLegalMovesPipelineAction_0; }
		
		//'LegalMovesPipeline'
		public Keyword getLegalMovesPipelineKeyword_1() { return cLegalMovesPipelineKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('filter' filter=[bg::Filter|EString])?
		public Group getGroup_3() { return cGroup_3; }
		
		//'filter'
		public Keyword getFilterKeyword_3_0() { return cFilterKeyword_3_0; }
		
		//filter=[bg::Filter|EString]
		public Assignment getFilterAssignment_3_1() { return cFilterAssignment_3_1; }
		
		//[bg::Filter|EString]
		public CrossReference getFilterFilterCrossReference_3_1_0() { return cFilterFilterCrossReference_3_1_0; }
		
		//EString
		public RuleCall getFilterFilterEStringParserRuleCall_3_1_0_1() { return cFilterFilterEStringParserRuleCall_3_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class EffectPipelineElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bgdsl.BgDsl.EffectPipeline");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEffectPipelineAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cEffectPipelineKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cFilterKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cFilterAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cFilterFilterCrossReference_3_1_0 = (CrossReference)cFilterAssignment_3_1.eContents().get(0);
		private final RuleCall cFilterFilterEStringParserRuleCall_3_1_0_1 = (RuleCall)cFilterFilterCrossReference_3_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//EffectPipeline returns bg::EffectPipeline:
		//    {bg::EffectPipeline}
		//    'EffectPipeline'
		//    '{'
		//        ('filter' filter=[bg::Filter|EString])?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{bg::EffectPipeline}
		//'EffectPipeline'
		//'{'
		//    ('filter' filter=[bg::Filter|EString])?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{bg::EffectPipeline}
		public Action getEffectPipelineAction_0() { return cEffectPipelineAction_0; }
		
		//'EffectPipeline'
		public Keyword getEffectPipelineKeyword_1() { return cEffectPipelineKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('filter' filter=[bg::Filter|EString])?
		public Group getGroup_3() { return cGroup_3; }
		
		//'filter'
		public Keyword getFilterKeyword_3_0() { return cFilterKeyword_3_0; }
		
		//filter=[bg::Filter|EString]
		public Assignment getFilterAssignment_3_1() { return cFilterAssignment_3_1; }
		
		//[bg::Filter|EString]
		public CrossReference getFilterFilterCrossReference_3_1_0() { return cFilterFilterCrossReference_3_1_0; }
		
		//EString
		public RuleCall getFilterFilterEStringParserRuleCall_3_1_0_1() { return cFilterFilterEStringParserRuleCall_3_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bgdsl.BgDsl.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//    'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class StateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bgdsl.BgDsl.State");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStateKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cHexColorKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cHexColorAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cHexColorEStringParserRuleCall_4_0 = (RuleCall)cHexColorAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cOutboundKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cOutboundAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cOutboundTransitionCrossReference_5_1_0 = (CrossReference)cOutboundAssignment_5_1.eContents().get(0);
		private final RuleCall cOutboundTransitionEStringParserRuleCall_5_1_0_1 = (RuleCall)cOutboundTransitionCrossReference_5_1_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cInboundKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cInboundAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cInboundTransitionCrossReference_6_1_0 = (CrossReference)cInboundAssignment_6_1.eContents().get(0);
		private final RuleCall cInboundTransitionEStringParserRuleCall_6_1_0_1 = (RuleCall)cInboundTransitionCrossReference_6_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//State returns bg::State:
		//    'State'
		//    name=EString
		//    '{'
		//        'hexColor' hexColor=EString
		//        ('outbound' outbound=[bg::Transition|EString])?
		//        ('inbound' inbound=[bg::Transition|EString])?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'State'
		//name=EString
		//'{'
		//    'hexColor' hexColor=EString
		//    ('outbound' outbound=[bg::Transition|EString])?
		//    ('inbound' inbound=[bg::Transition|EString])?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'State'
		public Keyword getStateKeyword_0() { return cStateKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'hexColor'
		public Keyword getHexColorKeyword_3() { return cHexColorKeyword_3; }
		
		//hexColor=EString
		public Assignment getHexColorAssignment_4() { return cHexColorAssignment_4; }
		
		//EString
		public RuleCall getHexColorEStringParserRuleCall_4_0() { return cHexColorEStringParserRuleCall_4_0; }
		
		//('outbound' outbound=[bg::Transition|EString])?
		public Group getGroup_5() { return cGroup_5; }
		
		//'outbound'
		public Keyword getOutboundKeyword_5_0() { return cOutboundKeyword_5_0; }
		
		//outbound=[bg::Transition|EString]
		public Assignment getOutboundAssignment_5_1() { return cOutboundAssignment_5_1; }
		
		//[bg::Transition|EString]
		public CrossReference getOutboundTransitionCrossReference_5_1_0() { return cOutboundTransitionCrossReference_5_1_0; }
		
		//EString
		public RuleCall getOutboundTransitionEStringParserRuleCall_5_1_0_1() { return cOutboundTransitionEStringParserRuleCall_5_1_0_1; }
		
		//('inbound' inbound=[bg::Transition|EString])?
		public Group getGroup_6() { return cGroup_6; }
		
		//'inbound'
		public Keyword getInboundKeyword_6_0() { return cInboundKeyword_6_0; }
		
		//inbound=[bg::Transition|EString]
		public Assignment getInboundAssignment_6_1() { return cInboundAssignment_6_1; }
		
		//[bg::Transition|EString]
		public CrossReference getInboundTransitionCrossReference_6_1_0() { return cInboundTransitionCrossReference_6_1_0; }
		
		//EString
		public RuleCall getInboundTransitionEStringParserRuleCall_6_1_0_1() { return cInboundTransitionEStringParserRuleCall_6_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class TransitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bgdsl.BgDsl.Transition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTransitionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cSourceKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cSourceAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cSourceStateCrossReference_5_0 = (CrossReference)cSourceAssignment_5.eContents().get(0);
		private final RuleCall cSourceStateEStringParserRuleCall_5_0_1 = (RuleCall)cSourceStateCrossReference_5_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCommaKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cSourceAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cSourceStateCrossReference_6_1_0 = (CrossReference)cSourceAssignment_6_1.eContents().get(0);
		private final RuleCall cSourceStateEStringParserRuleCall_6_1_0_1 = (RuleCall)cSourceStateCrossReference_6_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cTargetKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cTargetAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final CrossReference cTargetStateCrossReference_9_0 = (CrossReference)cTargetAssignment_9.eContents().get(0);
		private final RuleCall cTargetStateEStringParserRuleCall_9_0_1 = (RuleCall)cTargetStateCrossReference_9_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Transition returns bg::Transition:
		//    'Transition'
		//    name=EString
		//    '{'
		//        'source' '(' source+=[bg::State|EString] ( "," source+=[bg::State|EString])* ')'
		//        'target' target=[bg::State|EString]
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Transition'
		//name=EString
		//'{'
		//    'source' '(' source+=[bg::State|EString] ( "," source+=[bg::State|EString])* ')'
		//    'target' target=[bg::State|EString]
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Transition'
		public Keyword getTransitionKeyword_0() { return cTransitionKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'source'
		public Keyword getSourceKeyword_3() { return cSourceKeyword_3; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4() { return cLeftParenthesisKeyword_4; }
		
		//source+=[bg::State|EString]
		public Assignment getSourceAssignment_5() { return cSourceAssignment_5; }
		
		//[bg::State|EString]
		public CrossReference getSourceStateCrossReference_5_0() { return cSourceStateCrossReference_5_0; }
		
		//EString
		public RuleCall getSourceStateEStringParserRuleCall_5_0_1() { return cSourceStateEStringParserRuleCall_5_0_1; }
		
		//( "," source+=[bg::State|EString])*
		public Group getGroup_6() { return cGroup_6; }
		
		//","
		public Keyword getCommaKeyword_6_0() { return cCommaKeyword_6_0; }
		
		//source+=[bg::State|EString]
		public Assignment getSourceAssignment_6_1() { return cSourceAssignment_6_1; }
		
		//[bg::State|EString]
		public CrossReference getSourceStateCrossReference_6_1_0() { return cSourceStateCrossReference_6_1_0; }
		
		//EString
		public RuleCall getSourceStateEStringParserRuleCall_6_1_0_1() { return cSourceStateEStringParserRuleCall_6_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_7() { return cRightParenthesisKeyword_7; }
		
		//'target'
		public Keyword getTargetKeyword_8() { return cTargetKeyword_8; }
		
		//target=[bg::State|EString]
		public Assignment getTargetAssignment_9() { return cTargetAssignment_9; }
		
		//[bg::State|EString]
		public CrossReference getTargetStateCrossReference_9_0() { return cTargetStateCrossReference_9_0; }
		
		//EString
		public RuleCall getTargetStateEStringParserRuleCall_9_0_1() { return cTargetStateEStringParserRuleCall_9_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bgdsl.BgDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class SomeFilter1Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bgdsl.BgDsl.SomeFilter1");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSomeFilter1Action_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSomeFilter1Keyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cNextFilterKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cNextFilterAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNextFilterFilterParserRuleCall_3_1_0 = (RuleCall)cNextFilterAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//SomeFilter1 returns bg::SomeFilter1:
		//    {bg::SomeFilter1}
		//    'SomeFilter1'
		//    '{'
		//        ('nextFilter' nextFilter=Filter)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{bg::SomeFilter1}
		//'SomeFilter1'
		//'{'
		//    ('nextFilter' nextFilter=Filter)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{bg::SomeFilter1}
		public Action getSomeFilter1Action_0() { return cSomeFilter1Action_0; }
		
		//'SomeFilter1'
		public Keyword getSomeFilter1Keyword_1() { return cSomeFilter1Keyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('nextFilter' nextFilter=Filter)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'nextFilter'
		public Keyword getNextFilterKeyword_3_0() { return cNextFilterKeyword_3_0; }
		
		//nextFilter=Filter
		public Assignment getNextFilterAssignment_3_1() { return cNextFilterAssignment_3_1; }
		
		//Filter
		public RuleCall getNextFilterFilterParserRuleCall_3_1_0() { return cNextFilterFilterParserRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class SomeFilter2Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bgdsl.BgDsl.SomeFilter2");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSomeFilter2Action_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSomeFilter2Keyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cNextFilterKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cNextFilterAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNextFilterFilterParserRuleCall_3_1_0 = (RuleCall)cNextFilterAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//SomeFilter2 returns bg::SomeFilter2:
		//    {bg::SomeFilter2}
		//    'SomeFilter2'
		//    '{'
		//        ('nextFilter' nextFilter=Filter)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{bg::SomeFilter2}
		//'SomeFilter2'
		//'{'
		//    ('nextFilter' nextFilter=Filter)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{bg::SomeFilter2}
		public Action getSomeFilter2Action_0() { return cSomeFilter2Action_0; }
		
		//'SomeFilter2'
		public Keyword getSomeFilter2Keyword_1() { return cSomeFilter2Keyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('nextFilter' nextFilter=Filter)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'nextFilter'
		public Keyword getNextFilterKeyword_3_0() { return cNextFilterKeyword_3_0; }
		
		//nextFilter=Filter
		public Assignment getNextFilterAssignment_3_1() { return cNextFilterAssignment_3_1; }
		
		//Filter
		public RuleCall getNextFilterFilterParserRuleCall_3_1_0() { return cNextFilterFilterParserRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	
	public class TurnTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.bgdsl.BgDsl.TurnType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cTurnBasedEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cTurnBasedTurnBasedKeyword_0_0 = (Keyword)cTurnBasedEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cSimultaneousEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cSimultaneousSimultaneousKeyword_1_0 = (Keyword)cSimultaneousEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum TurnType returns bg::TurnType:
		//    TurnBased | Simultaneous;
		public EnumRule getRule() { return rule; }
		
		//TurnBased | Simultaneous
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//TurnBased
		public EnumLiteralDeclaration getTurnBasedEnumLiteralDeclaration_0() { return cTurnBasedEnumLiteralDeclaration_0; }
		
		public Keyword getTurnBasedTurnBasedKeyword_0_0() { return cTurnBasedTurnBasedKeyword_0_0; }
		
		//Simultaneous
		public EnumLiteralDeclaration getSimultaneousEnumLiteralDeclaration_1() { return cSimultaneousEnumLiteralDeclaration_1; }
		
		public Keyword getSimultaneousSimultaneousKeyword_1_0() { return cSimultaneousSimultaneousKeyword_1_0; }
	}
	
	private final PlayerElements pPlayer;
	private final TurnPolicyElements pTurnPolicy;
	private final TurnTypeElements eTurnType;
	private final GameElements pGame;
	private final BoardElements pBoard;
	private final FilterElements pFilter;
	private final EIntElements pEInt;
	private final TileElements pTile;
	private final LegalMovesPipelineElements pLegalMovesPipeline;
	private final EffectPipelineElements pEffectPipeline;
	private final EBooleanElements pEBoolean;
	private final StateElements pState;
	private final TransitionElements pTransition;
	private final EStringElements pEString;
	private final SomeFilter1Elements pSomeFilter1;
	private final SomeFilter2Elements pSomeFilter2;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public BgDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pPlayer = new PlayerElements();
		this.pTurnPolicy = new TurnPolicyElements();
		this.eTurnType = new TurnTypeElements();
		this.pGame = new GameElements();
		this.pBoard = new BoardElements();
		this.pFilter = new FilterElements();
		this.pEInt = new EIntElements();
		this.pTile = new TileElements();
		this.pLegalMovesPipeline = new LegalMovesPipelineElements();
		this.pEffectPipeline = new EffectPipelineElements();
		this.pEBoolean = new EBooleanElements();
		this.pState = new StateElements();
		this.pTransition = new TransitionElements();
		this.pEString = new EStringElements();
		this.pSomeFilter1 = new SomeFilter1Elements();
		this.pSomeFilter2 = new SomeFilter2Elements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("no.ntnu.tdt4250.bgdsl.BgDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Player returns bg::Player:
	//    'Player' name=EString;
	public PlayerElements getPlayerAccess() {
		return pPlayer;
	}
	
	public ParserRule getPlayerRule() {
		return getPlayerAccess().getRule();
	}
	
	//TurnPolicy returns bg::TurnPolicy:
	//    'TurnPolicy'
	//    '{'
	//        'type' type=TurnType
	//    '}';
	public TurnPolicyElements getTurnPolicyAccess() {
		return pTurnPolicy;
	}
	
	public ParserRule getTurnPolicyRule() {
		return getTurnPolicyAccess().getRule();
	}
	
	//enum TurnType returns bg::TurnType:
	//    TurnBased | Simultaneous;
	public TurnTypeElements getTurnTypeAccess() {
		return eTurnType;
	}
	
	public EnumRule getTurnTypeRule() {
		return getTurnTypeAccess().getRule();
	}
	
	//Game returns bg::Game:
	//    'Game' name=EString
	//    '{'
	//        'board' board=Board
	//        ('players' '{' players+=Player (',' players+=Player)* '}')?
	//        ('turnPolicy' '{' turnPolicy+=TurnPolicy (',' turnPolicy+=TurnPolicy)* '}')?
	//        ('initialPlayer' initialPlayer=[bg::Player|EString])?
	//    '}';
	public GameElements getGameAccess() {
		return pGame;
	}
	
	public ParserRule getGameRule() {
		return getGameAccess().getRule();
	}
	
	//Board returns bg::Board:
	//    checkered?='checkered'
	//    'Board'
	//    '{'
	//        'width' width=EInt
	//        'height' height=EInt
	//        'tiles' '{' tiles+=Tile ( "," tiles+=Tile)* '}'
	//        ('legalMovesPipeline' '{' legalMovesPipeline+=LegalMovesPipeline ( "," legalMovesPipeline+=LegalMovesPipeline)* '}' )?
	//        ('effectPipeline' '{' effectPipeline+=EffectPipeline ( "," effectPipeline+=EffectPipeline)* '}' )?
	//    '}';
	public BoardElements getBoardAccess() {
		return pBoard;
	}
	
	public ParserRule getBoardRule() {
		return getBoardAccess().getRule();
	}
	
	//Filter returns bg::Filter:
	//    SomeFilter1 | SomeFilter2;
	public FilterElements getFilterAccess() {
		return pFilter;
	}
	
	public ParserRule getFilterRule() {
		return getFilterAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    '-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//Tile returns bg::Tile:
	//    'Tile'
	//    '{'
	//        'row' row=EInt
	//        'col' col=EInt
	//        'color' color=EString
	//        'states' '{' states+=State ( "," states+=State)* '}'
	//        ('transitions' '{' transitions+=Transition ( "," transitions+=Transition)* '}' )?
	//        'initialState' initialState=State
	//    '}';
	public TileElements getTileAccess() {
		return pTile;
	}
	
	public ParserRule getTileRule() {
		return getTileAccess().getRule();
	}
	
	//LegalMovesPipeline returns bg::LegalMovesPipeline:
	//    {bg::LegalMovesPipeline}
	//    'LegalMovesPipeline'
	//    '{'
	//        ('filter' filter=[bg::Filter|EString])?
	//    '}';
	public LegalMovesPipelineElements getLegalMovesPipelineAccess() {
		return pLegalMovesPipeline;
	}
	
	public ParserRule getLegalMovesPipelineRule() {
		return getLegalMovesPipelineAccess().getRule();
	}
	
	//EffectPipeline returns bg::EffectPipeline:
	//    {bg::EffectPipeline}
	//    'EffectPipeline'
	//    '{'
	//        ('filter' filter=[bg::Filter|EString])?
	//    '}';
	public EffectPipelineElements getEffectPipelineAccess() {
		return pEffectPipeline;
	}
	
	public ParserRule getEffectPipelineRule() {
		return getEffectPipelineAccess().getRule();
	}
	
	//EBoolean returns ecore::EBoolean:
	//    'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//State returns bg::State:
	//    'State'
	//    name=EString
	//    '{'
	//        'hexColor' hexColor=EString
	//        ('outbound' outbound=[bg::Transition|EString])?
	//        ('inbound' inbound=[bg::Transition|EString])?
	//    '}';
	public StateElements getStateAccess() {
		return pState;
	}
	
	public ParserRule getStateRule() {
		return getStateAccess().getRule();
	}
	
	//Transition returns bg::Transition:
	//    'Transition'
	//    name=EString
	//    '{'
	//        'source' '(' source+=[bg::State|EString] ( "," source+=[bg::State|EString])* ')'
	//        'target' target=[bg::State|EString]
	//    '}';
	public TransitionElements getTransitionAccess() {
		return pTransition;
	}
	
	public ParserRule getTransitionRule() {
		return getTransitionAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//SomeFilter1 returns bg::SomeFilter1:
	//    {bg::SomeFilter1}
	//    'SomeFilter1'
	//    '{'
	//        ('nextFilter' nextFilter=Filter)?
	//    '}';
	public SomeFilter1Elements getSomeFilter1Access() {
		return pSomeFilter1;
	}
	
	public ParserRule getSomeFilter1Rule() {
		return getSomeFilter1Access().getRule();
	}
	
	//SomeFilter2 returns bg::SomeFilter2:
	//    {bg::SomeFilter2}
	//    'SomeFilter2'
	//    '{'
	//        ('nextFilter' nextFilter=Filter)?
	//    '}';
	public SomeFilter2Elements getSomeFilter2Access() {
		return pSomeFilter2;
	}
	
	public ParserRule getSomeFilter2Rule() {
		return getSomeFilter2Access().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
