/**
 * generated by Xtext 2.39.0
 */
package no.ntnu.tdt4250.bg.bgdsl.generator;

import java.util.Objects;
import java.util.Set;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.emf.ecore.EStructuralFeature;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class BgDslGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    EObject _head = IterableExtensions.<EObject>head(resource.getContents());
    final EObject gameInstance = ((EObject) _head);
    final EClass gameEClass = gameInstance.eClass();
    final Function1<EObject, EClass> _function = (EObject it) -> {
      return it.eClass();
    };
    final Set<EClass> allUniqueEClasses = IterableExtensions.<EClass>toSet(IterableExtensions.<EObject, EClass>map(IteratorExtensions.<EObject>toIterable(gameInstance.eAllContents()), _function));
    allUniqueEClasses.add(gameEClass);
    if ((gameInstance == null)) {
      System.err.println("Model resource is empty. Cannot generate data.");
      return;
    }
    System.out.println("Generating code with model instance data...");
    fsa.generateFile(
      ("models" + ".py"), 
      this.compileModels(allUniqueEClasses, gameInstance));
  }

  public CharSequence compileModels(final Set<EClass> models, final EObject gameInstance) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("from typing import List, Optional");
    _builder.newLine();
    _builder.append("from pydantic import BaseModel");
    _builder.newLine();
    _builder.newLine();
    {
      for(final EClass model : models) {
        _builder.append("class ");
        String _name = model.getName();
        _builder.append(_name);
        _builder.append("(BaseModel):");
        _builder.newLineIfNotEmpty();
        {
          boolean _isEmpty = model.getEAllStructuralFeatures().isEmpty();
          if (_isEmpty) {
            _builder.append("\t");
            _builder.append("pass");
            _builder.newLine();
          } else {
            {
              EList<EStructuralFeature> _eAllStructuralFeatures = model.getEAllStructuralFeatures();
              for(final EStructuralFeature field : _eAllStructuralFeatures) {
                CharSequence _pythonFieldDec = this.toPythonFieldDec(field);
                _builder.append(_pythonFieldDec);
                _builder.newLineIfNotEmpty();
              }
            }
          }
        }
        _builder.newLine();
      }
    }
    {
      for(final EClass model_1 : models) {
        String _name_1 = model_1.getName();
        _builder.append(_name_1);
        _builder.append(".model_rebuild()");
        _builder.newLineIfNotEmpty();
      }
    }
    CharSequence _initializeValues = this.initializeValues(gameInstance);
    _builder.append(_initializeValues);
    _builder.newLineIfNotEmpty();
    return _builder;
  }

  public CharSequence initializeValues(final EObject gameInstance) {
    CharSequence _xblockexpression = null;
    {
      Object _eGet = gameInstance.eGet(gameInstance.eClass().getEStructuralFeature("board"));
      final EObject boardInstance = ((EObject) _eGet);
      Object _eGet_1 = boardInstance.eGet(boardInstance.eClass().getEStructuralFeature("width"));
      final Integer width = ((Integer) _eGet_1);
      Object _eGet_2 = boardInstance.eGet(boardInstance.eClass().getEStructuralFeature("height"));
      final Integer height = ((Integer) _eGet_2);
      Object _eGet_3 = boardInstance.eGet(boardInstance.eClass().getEStructuralFeature("tiles"));
      final EList<EObject> tiles = ((EList<EObject>) _eGet_3);
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("tiles = [");
      _builder.newLine();
      {
        for(final EObject tile : tiles) {
          _builder.append("Tile(");
          Object _eGet_4 = tile.eGet(tile.eClass().getEStructuralFeature("name"));
          _builder.append(_eGet_4);
          _builder.append(")");
          _builder.newLineIfNotEmpty();
        }
      }
      _builder.append("]");
      _builder.newLine();
      _xblockexpression = _builder;
    }
    return _xblockexpression;
  }

  public CharSequence toPythonFieldDec(final EStructuralFeature field) {
    CharSequence _xblockexpression = null;
    {
      final String typeStr = this.pythonTypeString(field);
      CharSequence _xifexpression = null;
      boolean _isMany = field.isMany();
      if (_isMany) {
        StringConcatenation _builder = new StringConcatenation();
        _builder.append("\t");
        String _name = field.getName();
        _builder.append(_name, "\t");
        _builder.append(": List[\"");
        _builder.append(typeStr, "\t");
        _builder.append("\"] = []");
        _xifexpression = _builder;
      } else {
        CharSequence _xifexpression_1 = null;
        int _lowerBound = field.getLowerBound();
        boolean _equals = (_lowerBound == 0);
        if (_equals) {
          StringConcatenation _builder_1 = new StringConcatenation();
          _builder_1.append("\t");
          String _name_1 = field.getName();
          _builder_1.append(_name_1, "\t");
          _builder_1.append(": Optional[\"");
          _builder_1.append(typeStr, "\t");
          _builder_1.append("\"] = None");
          _xifexpression_1 = _builder_1;
        } else {
          StringConcatenation _builder_2 = new StringConcatenation();
          _builder_2.append("\t");
          String _name_2 = field.getName();
          _builder_2.append(_name_2, "\t");
          _builder_2.append(": \"");
          _builder_2.append(typeStr, "\t");
          _builder_2.append("\"");
          _xifexpression_1 = _builder_2;
        }
        _xifexpression = _xifexpression_1;
      }
      _xblockexpression = _xifexpression;
    }
    return _xblockexpression;
  }

  public String pythonTypeString(final EStructuralFeature field) {
    String _switchResult = null;
    boolean _matched = false;
    if (field instanceof EAttribute) {
      _matched=true;
      String _xblockexpression = null;
      {
        final String icn = ((EAttribute)field).getEAttributeType().getInstanceClassName();
        String _xifexpression = null;
        if ((Objects.equals(icn, "int") || Objects.equals(icn, "java.lang.Integer"))) {
          _xifexpression = "int";
        } else {
          String _xifexpression_1 = null;
          if ((Objects.equals(icn, "boolean") || Objects.equals(icn, "java.lang.Boolean"))) {
            _xifexpression_1 = "bool";
          } else {
            _xifexpression_1 = "str";
          }
          _xifexpression = _xifexpression_1;
        }
        _xblockexpression = _xifexpression;
      }
      _switchResult = _xblockexpression;
    }
    if (!_matched) {
      if (field instanceof EReference) {
        _matched=true;
        String _xblockexpression = null;
        {
          final EClass refType = ((EReference) field).getEReferenceType();
          _xblockexpression = refType.getName();
        }
        _switchResult = _xblockexpression;
      }
    }
    if (!_matched) {
      _switchResult = "str";
    }
    return _switchResult;
  }

  public CharSequence compileStructural(final EClass c) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("class ");
    String _name = c.getName();
    _builder.append(_name);
    _builder.append(":");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("def __init__(self, **kwargs):");
    _builder.newLine();
    {
      EList<EStructuralFeature> _eAllStructuralFeatures = c.getEAllStructuralFeatures();
      for(final EStructuralFeature feature : _eAllStructuralFeatures) {
        _builder.append("\t");
        _builder.append("self.");
        String _name_1 = feature.getName();
        _builder.append(_name_1, "\t");
        _builder.append(" = kwargs.get(\"");
        String _name_2 = feature.getName();
        _builder.append(_name_2, "\t");
        _builder.append("\", ");
        String _compileInitialization = this.compileInitialization(feature);
        _builder.append(_compileInitialization, "\t");
        _builder.append(")");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.newLine();
    _builder.append("\t");
    _builder.append("def __str__(self):");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return \"Instance of ");
    String _name_3 = c.getName();
    _builder.append(_name_3, "\t\t");
    _builder.append("\"");
    _builder.newLineIfNotEmpty();
    return _builder;
  }

  public CharSequence compileWithData(final EObject instance) {
    CharSequence _xblockexpression = null;
    {
      EClass _eClass = instance.eClass();
      final EClass eClass = ((EClass) _eClass);
      final Function1<EStructuralFeature, Boolean> _function = (EStructuralFeature it) -> {
        String _name = it.getName();
        return Boolean.valueOf(Objects.equals(_name, "name"));
      };
      final EStructuralFeature nameFeature = IterableExtensions.<EStructuralFeature>findFirst(eClass.getEStructuralFeatures(), _function);
      Object _eGet = instance.eGet(nameFeature);
      final String name = ((String) _eGet);
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("class ");
      String _name = eClass.getName();
      _builder.append(_name);
      _builder.append(":");
      _builder.newLineIfNotEmpty();
      _builder.newLine();
      _builder.append("\t");
      _builder.append("# Data pulled directly from the textual model instance and hardcoded");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("name = ");
      _builder.append(name, "\t");
      _builder.newLineIfNotEmpty();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("def __init__(self):");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("self.name = name");
      _builder.newLine();
      _builder.newLine();
      _builder.append("\t");
      _builder.append("def __str__(self):");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("return \"Game with name ");
      _builder.append(name, "\t\t");
      _builder.append("\"");
      _builder.newLineIfNotEmpty();
      _xblockexpression = _builder;
    }
    return _xblockexpression;
  }

  public String compileInitialization(final EStructuralFeature feature) {
    String _xifexpression = null;
    boolean _isMany = feature.isMany();
    if (_isMany) {
      _xifexpression = "[]";
    } else {
      _xifexpression = "None";
    }
    return _xifexpression;
  }
}
