/**
 * generated by Xtext 2.39.0
 */
package no.ntnu.tdt4250.bg.bgdsl.generator;

import java.util.Objects;
import java.util.Set;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.emf.ecore.EStructuralFeature;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import org.eclipse.xtext.xbase.lib.ListExtensions;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class BgDslGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    EObject _head = IterableExtensions.<EObject>head(resource.getContents());
    final EObject gameInstance = ((EObject) _head);
    final EClass gameEClass = gameInstance.eClass();
    final Function1<EObject, EClass> _function = (EObject it) -> {
      return it.eClass();
    };
    final Set<EClass> allUniqueEClasses = IterableExtensions.<EClass>toSet(IterableExtensions.<EObject, EClass>map(IteratorExtensions.<EObject>toIterable(gameInstance.eAllContents()), _function));
    allUniqueEClasses.add(gameEClass);
    if ((gameInstance == null)) {
      System.err.println("Model resource is empty. Cannot generate data.");
      return;
    }
    System.out.println("Generating code with model instance data...");
    fsa.generateFile(
      ("models" + ".py"), 
      this.compileModels(allUniqueEClasses, gameInstance));
  }

  public CharSequence compileModels(final Set<EClass> models, final EObject gameInstance) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("from typing import List, Optional");
    _builder.newLine();
    _builder.append("from pydantic import BaseModel");
    _builder.newLine();
    _builder.newLine();
    _builder.append("class Filter(BaseModel):");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("pass");
    _builder.newLine();
    _builder.newLine();
    {
      for(final EClass model : models) {
        {
          String _name = model.getName();
          boolean _equals = Objects.equals(_name, "TilePlacement");
          if (_equals) {
          } else {
            {
              String _name_1 = model.getName();
              boolean _equals_1 = Objects.equals(_name_1, "PatternFilter");
              if (_equals_1) {
                _builder.append("class ");
                String _name_2 = model.getName();
                _builder.append(_name_2);
                _builder.append("(Filter):");
                _builder.newLineIfNotEmpty();
              } else {
                _builder.append("class ");
                String _name_3 = model.getName();
                _builder.append(_name_3);
                _builder.append("(BaseModel):");
                _builder.newLineIfNotEmpty();
              }
            }
            {
              boolean _isEmpty = model.getEAllStructuralFeatures().isEmpty();
              if (_isEmpty) {
                _builder.append("    ");
                _builder.append("pass");
                _builder.newLine();
              } else {
                {
                  String _name_4 = model.getName();
                  boolean _equals_2 = Objects.equals(_name_4, "Tile");
                  if (_equals_2) {
                    {
                      EList<EStructuralFeature> _eAllStructuralFeatures = model.getEAllStructuralFeatures();
                      for(final EStructuralFeature field : _eAllStructuralFeatures) {
                        _builder.append("    ");
                        CharSequence _pythonFieldDec = this.toPythonFieldDec(field);
                        _builder.append(_pythonFieldDec, "    ");
                        _builder.newLineIfNotEmpty();
                      }
                    }
                    _builder.append("    ");
                    _builder.append("activeState: \"State\"");
                    _builder.newLine();
                    _builder.append("    ");
                    _builder.append("row: \"int\"");
                    _builder.newLine();
                    _builder.append("    ");
                    _builder.append("column: \"int\"");
                    _builder.newLine();
                    _builder.newLine();
                    _builder.append("    ");
                    _builder.append("def updateState(self, targetStateName: str):");
                    _builder.newLine();
                    _builder.append("    ");
                    _builder.append("    ");
                    _builder.append("for transition in self.transitions:");
                    _builder.newLine();
                    _builder.append("    ");
                    _builder.append("        ");
                    _builder.append("for source in transition.source:");
                    _builder.newLine();
                    _builder.append("    ");
                    _builder.append("            ");
                    _builder.append("if source.name == self.activeState.name and transition.target.name == targetStateName:");
                    _builder.newLine();
                    _builder.append("    ");
                    _builder.append("                ");
                    _builder.append("self.activeState = transition.target");
                    _builder.newLine();
                    _builder.newLine();
                  } else {
                    String _name_5 = model.getName();
                    boolean _equals_3 = Objects.equals(_name_5, "Board");
                    if (_equals_3) {
                      _builder.append("    ");
                      _builder.append("width: \"int\"");
                      _builder.newLine();
                      _builder.append("    ");
                      _builder.append("tiles: List[\"Tile\"] = []");
                      _builder.newLine();
                      _builder.append("    ");
                      _builder.append("legalMovesPipeline: Optional[\"LegalMovesPipeline\"] = None");
                      _builder.newLine();
                      _builder.append("    ");
                      _builder.append("effectPipeline: Optional[\"EffectPipeline\"] = None");
                      _builder.newLine();
                      _builder.append("    ");
                      _builder.append("height: \"int\"");
                      _builder.newLine();
                      _builder.append("    ");
                      _builder.append("checkered: \"bool\"");
                      _builder.newLine();
                      _builder.append("    ");
                      _builder.append("size: \"int\"");
                      _builder.newLine();
                      _builder.append("    ");
                      _builder.append("legalMoves: List[\"Tile\"] = []");
                      _builder.newLine();
                      _builder.append("    ");
                      _builder.newLine();
                    } else {
                      String _name_6 = model.getName();
                      boolean _equals_4 = Objects.equals(_name_6, "Pattern");
                      if (_equals_4) {
                        _builder.append("    ");
                        _builder.append("relativecoordinates: List[\"RelativeCoordinate\"] = []");
                        _builder.newLine();
                        _builder.append("    ");
                        _builder.append("name: \"str\"");
                        _builder.newLine();
                        _builder.append("    ");
                        _builder.append("stateSelection: Optional[\"str\"] = None");
                        _builder.newLine();
                        _builder.append("    ");
                        _builder.append("matchState: Optional[\"str\"] = None");
                        _builder.newLine();
                        _builder.append("    ");
                        _builder.newLine();
                      } else {
                        String _name_7 = model.getName();
                        boolean _equals_5 = Objects.equals(_name_7, "Player");
                        if (_equals_5) {
                          _builder.append("    ");
                          _builder.append("name: \"str\"");
                          _builder.newLine();
                          _builder.append("    ");
                          _builder.append("hexColor: \"str\"");
                          _builder.newLine();
                          _builder.append("    ");
                          _builder.append("associatedState: \"str\"");
                          _builder.newLine();
                          _builder.newLine();
                        } else {
                          {
                            EList<EStructuralFeature> _eAllStructuralFeatures_1 = model.getEAllStructuralFeatures();
                            for(final EStructuralFeature field_1 : _eAllStructuralFeatures_1) {
                              _builder.append("    ");
                              CharSequence _pythonFieldDec_1 = this.toPythonFieldDec(field_1);
                              _builder.append(_pythonFieldDec_1, "    ");
                              _builder.newLineIfNotEmpty();
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
            _builder.append("    ");
            _builder.newLine();
          }
        }
      }
    }
    _builder.newLine();
    {
      for(final EClass model_1 : models) {
        {
          String _name_8 = model_1.getName();
          boolean _equals_6 = Objects.equals(_name_8, "TilePlacement");
          if (_equals_6) {
          } else {
            String _name_9 = model_1.getName();
            _builder.append(_name_9);
            _builder.append(".model_rebuild()");
            _builder.newLineIfNotEmpty();
          }
        }
      }
    }
    _builder.newLine();
    CharSequence _initializeValues = this.initializeValues(gameInstance);
    _builder.append(_initializeValues);
    _builder.newLineIfNotEmpty();
    return _builder;
  }

  public CharSequence initializeValues(final EObject gameInstance) {
    CharSequence _xblockexpression = null;
    {
      Object _feature = this.getFeature(gameInstance, "board");
      final EObject boardInstance = ((EObject) _feature);
      Object _feature_1 = this.getFeature(boardInstance, "tiles");
      final EList<EObject> tileTypes = ((EList<EObject>) _feature_1);
      Object _feature_2 = this.getFeature(boardInstance, "tileplacement");
      final EList<EObject> tilePlacements = ((EList<EObject>) _feature_2);
      Object _feature_3 = this.getFeature(gameInstance, "players");
      final EList<EObject> players = ((EList<EObject>) _feature_3);
      StringConcatenation _builder = new StringConcatenation();
      {
        for(final EObject tileType : tileTypes) {
          final Object tileName = this.getFeature(tileType, "name");
          _builder.newLineIfNotEmpty();
          Object _feature_4 = this.getFeature(tileType, "initialState");
          final EObject initState = ((EObject) _feature_4);
          _builder.newLineIfNotEmpty();
          final Object initName = this.getFeature(initState, "name");
          _builder.newLineIfNotEmpty();
          final Object initColor = this.getFeature(initState, "hexColor");
          _builder.newLineIfNotEmpty();
          Object _feature_5 = this.getFeature(tileType, "states");
          final EList<EObject> states = ((EList<EObject>) _feature_5);
          _builder.newLineIfNotEmpty();
          Object _feature_6 = this.getFeature(tileType, "transitions");
          final EList<EObject> transitions = ((EList<EObject>) _feature_6);
          _builder.newLineIfNotEmpty();
          final Object tileColor = this.getFeature(tileType, "hexColor");
          _builder.newLineIfNotEmpty();
          _builder.newLine();
          _builder.append("class ");
          _builder.append(tileName);
          _builder.append("(Tile):");
          _builder.newLineIfNotEmpty();
          _builder.append("    ");
          _builder.append("def __init__(self, row, column):");
          _builder.newLine();
          _builder.append("        ");
          _builder.append("state");
          _builder.append(initName, "        ");
          _builder.append(" = State(");
          _builder.newLineIfNotEmpty();
          _builder.append("            ");
          _builder.append("name=\"");
          _builder.append(initName, "            ");
          _builder.append("\",");
          _builder.newLineIfNotEmpty();
          _builder.append("            ");
          _builder.append("hexColor=\"");
          _builder.append(initColor, "            ");
          _builder.append("\",");
          _builder.newLineIfNotEmpty();
          _builder.append("            ");
          _builder.append("outbound=[]");
          _builder.newLine();
          _builder.append("        ");
          _builder.append(")");
          _builder.newLine();
          _builder.newLine();
          _builder.append("        ");
          _builder.append("row = row");
          _builder.newLine();
          _builder.append("        ");
          _builder.append("column = column");
          _builder.newLine();
          _builder.newLine();
          {
            for(final EObject state : states) {
              _builder.append("        ");
              _builder.append("    ");
              final Object sName = this.getFeature(state, "name");
              _builder.newLineIfNotEmpty();
              _builder.append("        ");
              _builder.append("state");
              _builder.append(sName, "        ");
              _builder.append(" = State(");
              _builder.newLineIfNotEmpty();
              _builder.append("        ");
              _builder.append("    ");
              _builder.append("name=\"");
              _builder.append(sName, "            ");
              _builder.append("\",");
              _builder.newLineIfNotEmpty();
              _builder.append("        ");
              _builder.append("    ");
              _builder.append("hexColor=\"#ffffff\",");
              _builder.newLine();
              _builder.append("        ");
              _builder.append("    ");
              _builder.append("outbound=[],");
              _builder.newLine();
              _builder.append("        ");
              _builder.append("    ");
              _builder.append("inbound=[]");
              _builder.newLine();
              _builder.append("        ");
              _builder.append(")");
              _builder.newLine();
            }
          }
          _builder.newLine();
          {
            for(final EObject transition : transitions) {
              _builder.append("        ");
              _builder.append("    ");
              final Object tName = this.getFeature(transition, "name");
              _builder.newLineIfNotEmpty();
              _builder.append("        ");
              _builder.append("    ");
              Object _feature_7 = this.getFeature(transition, "source");
              final EList<EObject> rawSources = ((EList<EObject>) _feature_7);
              _builder.newLineIfNotEmpty();
              _builder.append("        ");
              _builder.append("    ");
              final Set<EObject> srcList = IterableExtensions.<EObject>toSet(rawSources);
              _builder.newLineIfNotEmpty();
              _builder.append("        ");
              _builder.append("    ");
              Object _feature_8 = this.getFeature(transition, "target");
              final EObject target = ((EObject) _feature_8);
              _builder.newLineIfNotEmpty();
              _builder.append("        ");
              _builder.append("transition");
              _builder.append(tName, "        ");
              _builder.append(" = Transition(");
              _builder.newLineIfNotEmpty();
              _builder.append("        ");
              _builder.append("    ");
              _builder.append("name=\"");
              _builder.append(tName, "            ");
              _builder.append("\",");
              _builder.newLineIfNotEmpty();
              _builder.append("        ");
              _builder.append("    ");
              _builder.append("source=[");
              _builder.newLine();
              {
                boolean _hasElements = false;
                for(final EObject src : srcList) {
                  if (!_hasElements) {
                    _hasElements = true;
                  } else {
                    _builder.appendImmediate(", ", "                ");
                  }
                  _builder.append("        ");
                  _builder.append("        ");
                  _builder.append("state");
                  Object _feature_9 = this.getFeature(src, "name");
                  _builder.append(_feature_9, "                ");
                  _builder.newLineIfNotEmpty();
                }
              }
              _builder.append("        ");
              _builder.append("    ");
              _builder.append("],");
              _builder.newLine();
              _builder.append("        ");
              _builder.append("    ");
              _builder.append("target=state");
              Object _feature_10 = this.getFeature(target, "name");
              _builder.append(_feature_10, "            ");
              _builder.newLineIfNotEmpty();
              _builder.append("        ");
              _builder.append(")");
              _builder.newLine();
            }
          }
          _builder.newLine();
          {
            for(final EObject transition_1 : transitions) {
              _builder.append("        ");
              _builder.append("    ");
              final Object tName_1 = this.getFeature(transition_1, "name");
              _builder.newLineIfNotEmpty();
              _builder.append("        ");
              _builder.append("    ");
              Object _feature_11 = this.getFeature(transition_1, "source");
              final EList<EObject> rawSources_1 = ((EList<EObject>) _feature_11);
              _builder.newLineIfNotEmpty();
              _builder.append("        ");
              _builder.append("    ");
              final Set<EObject> srcList_1 = IterableExtensions.<EObject>toSet(rawSources_1);
              _builder.newLineIfNotEmpty();
              {
                for(final EObject src_1 : srcList_1) {
                  _builder.append("        ");
                  _builder.append("state");
                  Object _feature_12 = this.getFeature(src_1, "name");
                  _builder.append(_feature_12, "        ");
                  _builder.append(".outbound.append(transition");
                  _builder.append(tName_1, "        ");
                  _builder.append(")");
                  _builder.newLineIfNotEmpty();
                }
              }
              _builder.append("        ");
              _builder.append("    ");
              Object _feature_13 = this.getFeature(transition_1, "target");
              final EObject target_1 = ((EObject) _feature_13);
              _builder.newLineIfNotEmpty();
              _builder.append("        ");
              _builder.append("state");
              Object _feature_14 = this.getFeature(target_1, "name");
              _builder.append(_feature_14, "        ");
              _builder.append(".inbound.append(transition");
              _builder.append(tName_1, "        ");
              _builder.append(")");
              _builder.newLineIfNotEmpty();
            }
          }
          _builder.newLine();
          _builder.append("        ");
          _builder.append("super().__init__(");
          _builder.newLine();
          _builder.append("            ");
          _builder.append("states=[");
          _builder.newLine();
          {
            boolean _hasElements_1 = false;
            for(final EObject state_1 : states) {
              if (!_hasElements_1) {
                _hasElements_1 = true;
              } else {
                _builder.appendImmediate(", ", "                ");
              }
              _builder.append("                ");
              _builder.append("state");
              Object _feature_15 = this.getFeature(state_1, "name");
              _builder.append(_feature_15, "                ");
              _builder.newLineIfNotEmpty();
            }
          }
          _builder.append("            ");
          _builder.append("],");
          _builder.newLine();
          _builder.append("            ");
          _builder.append("transitions=[");
          _builder.newLine();
          {
            boolean _hasElements_2 = false;
            for(final EObject transition_2 : transitions) {
              if (!_hasElements_2) {
                _hasElements_2 = true;
              } else {
                _builder.appendImmediate(", ", "                ");
              }
              _builder.append("                ");
              _builder.append("transition");
              Object _feature_16 = this.getFeature(transition_2, "name");
              _builder.append(_feature_16, "                ");
              _builder.newLineIfNotEmpty();
            }
          }
          _builder.append("            ");
          _builder.append("],");
          _builder.newLine();
          _builder.append("            ");
          _builder.append("initialState=state");
          Object _feature_17 = this.getFeature(initState, "name");
          _builder.append(_feature_17, "            ");
          _builder.append(",");
          _builder.newLineIfNotEmpty();
          _builder.append("            ");
          _builder.append("activeState=state");
          Object _feature_18 = this.getFeature(initState, "name");
          _builder.append(_feature_18, "            ");
          _builder.append(",");
          _builder.newLineIfNotEmpty();
          _builder.append("            ");
          _builder.append("tileType=\"");
          _builder.append(tileName, "            ");
          _builder.append("\",");
          _builder.newLineIfNotEmpty();
          _builder.append("            ");
          _builder.append("hexColor=\"");
          _builder.append(tileColor, "            ");
          _builder.append("\",");
          _builder.newLineIfNotEmpty();
          _builder.append("            ");
          _builder.append("name=\"");
          _builder.append(tileName, "            ");
          _builder.append("\",");
          _builder.newLineIfNotEmpty();
          _builder.append("            ");
          _builder.append("row=row,");
          _builder.newLine();
          _builder.append("            ");
          _builder.append("column=column");
          _builder.newLine();
          _builder.append("        ");
          _builder.append(")");
          _builder.newLine();
          _builder.newLine();
        }
      }
      _builder.newLine();
      _builder.append("tiles = [");
      _builder.newLine();
      {
        boolean _hasElements_3 = false;
        for(final EObject tilePlacement : tilePlacements) {
          if (!_hasElements_3) {
            _hasElements_3 = true;
          } else {
            _builder.appendImmediate(", ", "    ");
          }
          _builder.append("    ");
          Object _feature_19 = this.getFeature(tilePlacement, "tile");
          final EObject tile = ((EObject) _feature_19);
          _builder.newLineIfNotEmpty();
          _builder.append("    ");
          final Object tileType_1 = this.getFeature(tile, "name");
          _builder.newLineIfNotEmpty();
          _builder.append("    ");
          Object _feature_20 = this.getFeature(tilePlacement, "row");
          final Integer tileRow = ((Integer) _feature_20);
          _builder.newLineIfNotEmpty();
          _builder.append("    ");
          Object _feature_21 = this.getFeature(tilePlacement, "column");
          final Integer tileColumn = ((Integer) _feature_21);
          _builder.newLineIfNotEmpty();
          _builder.append("    ");
          _builder.append(tileType_1, "    ");
          _builder.append("(");
          _builder.append(tileRow, "    ");
          _builder.append(", ");
          _builder.append(tileColumn, "    ");
          _builder.append(")");
          _builder.newLineIfNotEmpty();
        }
      }
      _builder.append("]");
      _builder.newLine();
      _builder.newLine();
      _builder.append("players = [");
      _builder.newLine();
      {
        boolean _hasElements_4 = false;
        for(final EObject player : players) {
          if (!_hasElements_4) {
            _hasElements_4 = true;
          } else {
            _builder.appendImmediate(", ", "    ");
          }
          _builder.append("    ");
          Object _feature_22 = this.getFeature(player, "name");
          final String playerName = ((String) _feature_22);
          _builder.newLineIfNotEmpty();
          _builder.append("    ");
          Object _feature_23 = this.getFeature(player, "hexColor");
          final String playerColor = ((String) _feature_23);
          _builder.newLineIfNotEmpty();
          _builder.append("    ");
          Object _feature_24 = this.getFeature(player, "associatedState");
          final EObject associatedState = ((EObject) _feature_24);
          _builder.newLineIfNotEmpty();
          _builder.append("    ");
          _builder.append("Player(");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("    ");
          _builder.append("name=\"");
          _builder.append(playerName, "        ");
          _builder.append("\",");
          _builder.newLineIfNotEmpty();
          _builder.append("    ");
          _builder.append("    ");
          _builder.append("hexColor=\"");
          _builder.append(playerColor, "        ");
          _builder.append("\",");
          _builder.newLineIfNotEmpty();
          _builder.append("    ");
          _builder.append("    ");
          _builder.append("associatedState=\"");
          Object _feature_25 = this.getFeature(associatedState, "name");
          _builder.append(_feature_25, "        ");
          _builder.append("\"");
          _builder.newLineIfNotEmpty();
          _builder.append("    ");
          _builder.append(")");
          _builder.newLine();
        }
      }
      _builder.append("]");
      _builder.newLine();
      _builder.newLine();
      Object _feature_26 = this.getFeature(boardInstance, "width");
      final Integer boardWidth = ((Integer) _feature_26);
      _builder.newLineIfNotEmpty();
      Object _feature_27 = this.getFeature(boardInstance, "height");
      final Integer boardHeight = ((Integer) _feature_27);
      _builder.newLineIfNotEmpty();
      Object _feature_28 = this.getFeature(boardInstance, "checkered");
      final Boolean isCheckered = ((Boolean) _feature_28);
      _builder.newLineIfNotEmpty();
      Object _feature_29 = this.getFeature(boardInstance, "legalMovesPipeline");
      final EObject legalPipelineObj = ((EObject) _feature_29);
      _builder.newLineIfNotEmpty();
      String _xifexpression = null;
      if ((legalPipelineObj != null)) {
        String _xblockexpression_1 = null;
        {
          Object _feature_30 = this.getFeature(legalPipelineObj, "filter");
          final EObject filter = ((EObject) _feature_30);
          _xblockexpression_1 = this.renderFilter(filter);
        }
        _xifexpression = _xblockexpression_1;
      } else {
        _xifexpression = "";
      }
      final String legalMovesPipelineRendered = _xifexpression;
      _builder.newLineIfNotEmpty();
      Object _feature_30 = this.getFeature(boardInstance, "effectPipeline");
      final EObject effectPipelineObj = ((EObject) _feature_30);
      _builder.newLineIfNotEmpty();
      String _xifexpression_1 = null;
      if ((effectPipelineObj != null)) {
        String _xblockexpression_2 = null;
        {
          Object _feature_31 = this.getFeature(effectPipelineObj, "filter");
          final EObject filter = ((EObject) _feature_31);
          _xblockexpression_2 = this.renderFilter(filter);
        }
        _xifexpression_1 = _xblockexpression_2;
      } else {
        _xifexpression_1 = "";
      }
      final String effectPipelineRendered = _xifexpression_1;
      _builder.newLineIfNotEmpty();
      _builder.newLine();
      _builder.append("board = Board(");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("width=");
      _builder.append(boardWidth, "    ");
      _builder.append(",");
      _builder.newLineIfNotEmpty();
      _builder.append("    ");
      _builder.append("height=");
      _builder.append(boardHeight, "    ");
      _builder.append(",");
      _builder.newLineIfNotEmpty();
      _builder.append("    ");
      _builder.append("tiles=tiles,");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("checkered=");
      String _pyBool = this.toPyBool(isCheckered);
      _builder.append(_pyBool, "    ");
      _builder.append(",");
      _builder.newLineIfNotEmpty();
      _builder.append("    ");
      _builder.append("size=");
      _builder.append(((boardWidth).intValue() * (boardHeight).intValue()), "    ");
      _builder.append(",");
      _builder.newLineIfNotEmpty();
      {
        boolean _notEquals = (!Objects.equals(legalMovesPipelineRendered, ""));
        if (_notEquals) {
          _builder.append("    ");
          _builder.append("legalMovesPipeline=LegalMovesPipeline(filter=");
          _builder.append(legalMovesPipelineRendered, "    ");
          _builder.append("),");
          _builder.newLineIfNotEmpty();
        }
      }
      {
        boolean _notEquals_1 = (!Objects.equals(effectPipelineRendered, ""));
        if (_notEquals_1) {
          _builder.append("    ");
          _builder.append("effectPipeline=EffectPipeline(filter=");
          _builder.append(effectPipelineRendered, "    ");
          _builder.append("),");
          _builder.newLineIfNotEmpty();
        }
      }
      _builder.append("    ");
      _builder.append("legalMoves=[]");
      _builder.newLine();
      _builder.append(")");
      _builder.newLine();
      _builder.newLine();
      Object _feature_31 = this.getFeature(gameInstance, "initialPlayer");
      final EObject initialPlayer = ((EObject) _feature_31);
      _builder.newLineIfNotEmpty();
      final int initialPlayerIndex = players.indexOf(initialPlayer);
      _builder.newLineIfNotEmpty();
      Object _feature_32 = this.getFeature(gameInstance, "name");
      final String gameName = ((String) _feature_32);
      _builder.newLineIfNotEmpty();
      final Object turnPolicy = this.getFeature(gameInstance, "turnPolicy");
      _builder.newLineIfNotEmpty();
      _builder.newLine();
      _builder.append("game = Game(");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("board=board,");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("players=players,");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("activePlayer=players[");
      _builder.append(initialPlayerIndex, "    ");
      _builder.append("],");
      _builder.newLineIfNotEmpty();
      _builder.append("    ");
      _builder.append("name=\"");
      _builder.append(gameName, "    ");
      _builder.append("\",");
      _builder.newLineIfNotEmpty();
      _builder.append("    ");
      _builder.append("initialPlayer=players[");
      _builder.append(initialPlayerIndex, "    ");
      _builder.append("],");
      _builder.newLineIfNotEmpty();
      _builder.append("    ");
      _builder.append("turnPolicy=\"");
      _builder.append(turnPolicy, "    ");
      _builder.append("\"");
      _builder.newLineIfNotEmpty();
      _builder.append(")");
      _builder.newLine();
      _builder.newLine();
      _xblockexpression = _builder;
    }
    return _xblockexpression;
  }

  public String renderFilter(final EObject filter) {
    String _xblockexpression = null;
    {
      if ((filter == null)) {
        return "";
      }
      final Object filterName = this.getFeature(filter, "name");
      Object _feature = this.getFeature(filter, "nextFilter");
      final EObject nextFilter = ((EObject) _feature);
      Object _feature_1 = this.getFeature(filter, "patterns");
      final EList<EObject> patterns = ((EList<EObject>) _feature_1);
      String _xifexpression = null;
      if ((patterns != null)) {
        final Function1<EObject, String> _function = (EObject pattern) -> {
          String _xblockexpression_1 = null;
          {
            final Object patternName = this.getFeature(pattern, "name");
            final Object stateSelectionEnum = this.getFeature(pattern, "stateSelection");
            Object _xifexpression_1 = null;
            if ((stateSelectionEnum != null)) {
              _xifexpression_1 = stateSelectionEnum;
            } else {
              _xifexpression_1 = "null";
            }
            final Object stateSelectionName = _xifexpression_1;
            Object _feature_2 = this.getFeature(pattern, "matchState");
            final EObject matchStateObj = ((EObject) _feature_2);
            Object _xifexpression_2 = null;
            if ((matchStateObj != null)) {
              _xifexpression_2 = this.getFeature(matchStateObj, "name");
            } else {
              _xifexpression_2 = "null";
            }
            final Object matchStateName = _xifexpression_2;
            Object _feature_3 = this.getFeature(pattern, "relativecoordinates");
            final EList<EObject> relCoords = ((EList<EObject>) _feature_3);
            String _xifexpression_3 = null;
            if ((relCoords != null)) {
              final Function1<EObject, String> _function_1 = (EObject rc) -> {
                String _xblockexpression_2 = null;
                {
                  final Object rx = this.getFeature(rc, "x");
                  final Object ry = this.getFeature(rc, "y");
                  _xblockexpression_2 = (((("RelativeCoordinate(x=" + rx) + ", y=") + ry) + ")");
                }
                return _xblockexpression_2;
              };
              _xifexpression_3 = IterableExtensions.join(ListExtensions.<EObject, String>map(relCoords, _function_1), ", ");
            } else {
              _xifexpression_3 = "";
            }
            final String coordsRendered = _xifexpression_3;
            _xblockexpression_1 = (((((((("Pattern(\n                    name=\"" + patternName) + "\",\n                    stateSelection=\"") + stateSelectionName) + "\",\n                    matchState=\"") + matchStateName) + "\",\n                    relativecoordinates=[") + coordsRendered) + "]\n                )");
          }
          return _xblockexpression_1;
        };
        _xifexpression = IterableExtensions.join(ListExtensions.<EObject, String>map(patterns, _function), ", ");
      } else {
        _xifexpression = "";
      }
      final String patternsRendered = _xifexpression;
      String _xifexpression_1 = null;
      if ((nextFilter != null)) {
        String _renderFilter = this.renderFilter(nextFilter);
        _xifexpression_1 = (", nextFilter=" + _renderFilter);
      } else {
        _xifexpression_1 = "";
      }
      String _plus = ((((("PatternFilter(\n            name=\"" + filterName) + "\",\n            patterns=[") + patternsRendered) + "]") + _xifexpression_1);
      _xblockexpression = (_plus + 
        ")");
    }
    return _xblockexpression;
  }

  /**
   * Helper Code
   */
  public Object getFeature(final EObject self, final String feature) {
    final EStructuralFeature es = self.eClass().getEStructuralFeature(feature);
    if ((es == null)) {
      String _name = self.eClass().getName();
      String _plus = ((("Feature \'" + feature) + "\' not found on ") + _name);
      throw new IllegalArgumentException(_plus);
    }
    return self.eGet(es);
  }

  public CharSequence toPythonFieldDec(final EStructuralFeature field) {
    CharSequence _xblockexpression = null;
    {
      final String typeStr = this.pythonTypeString(field);
      CharSequence _xifexpression = null;
      boolean _isMany = field.isMany();
      if (_isMany) {
        StringConcatenation _builder = new StringConcatenation();
        String _name = field.getName();
        _builder.append(_name);
        _builder.append(": List[\"");
        _builder.append(typeStr);
        _builder.append("\"] = []");
        _xifexpression = _builder;
      } else {
        CharSequence _xifexpression_1 = null;
        int _lowerBound = field.getLowerBound();
        boolean _equals = (_lowerBound == 0);
        if (_equals) {
          StringConcatenation _builder_1 = new StringConcatenation();
          String _name_1 = field.getName();
          _builder_1.append(_name_1);
          _builder_1.append(": Optional[\"");
          _builder_1.append(typeStr);
          _builder_1.append("\"] = None");
          _xifexpression_1 = _builder_1;
        } else {
          StringConcatenation _builder_2 = new StringConcatenation();
          String _name_2 = field.getName();
          _builder_2.append(_name_2);
          _builder_2.append(": \"");
          _builder_2.append(typeStr);
          _builder_2.append("\"");
          _xifexpression_1 = _builder_2;
        }
        _xifexpression = _xifexpression_1;
      }
      _xblockexpression = _xifexpression;
    }
    return _xblockexpression;
  }

  public String pythonTypeString(final EStructuralFeature field) {
    String _switchResult = null;
    boolean _matched = false;
    if (field instanceof EAttribute) {
      _matched=true;
      String _xblockexpression = null;
      {
        final String icn = ((EAttribute)field).getEAttributeType().getInstanceClassName();
        String _xifexpression = null;
        if ((Objects.equals(icn, "int") || Objects.equals(icn, "java.lang.Integer"))) {
          _xifexpression = "int";
        } else {
          String _xifexpression_1 = null;
          if ((Objects.equals(icn, "boolean") || Objects.equals(icn, "java.lang.Boolean"))) {
            _xifexpression_1 = "bool";
          } else {
            _xifexpression_1 = "str";
          }
          _xifexpression = _xifexpression_1;
        }
        _xblockexpression = _xifexpression;
      }
      _switchResult = _xblockexpression;
    }
    if (!_matched) {
      if (field instanceof EReference) {
        _matched=true;
        String _xblockexpression = null;
        {
          final EClass refType = ((EReference) field).getEReferenceType();
          _xblockexpression = refType.getName();
        }
        _switchResult = _xblockexpression;
      }
    }
    if (!_matched) {
      _switchResult = "str";
    }
    return _switchResult;
  }

  public String toPyBool(final Boolean b) {
    String _xifexpression = null;
    if ((b).booleanValue()) {
      _xifexpression = "True";
    } else {
      _xifexpression = "False";
    }
    return _xifexpression;
  }
}
