/*
 * generated by Xtext 2.39.0
 */
package no.ntnu.tdt4250.bg.bgdsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import no.ntnu.tdt4250.bg.BgPackage;
import no.ntnu.tdt4250.bg.Board;
import no.ntnu.tdt4250.bg.EffectPipeline;
import no.ntnu.tdt4250.bg.Game;
import no.ntnu.tdt4250.bg.IterativeFilter;
import no.ntnu.tdt4250.bg.LegalMovesPipeline;
import no.ntnu.tdt4250.bg.Pattern;
import no.ntnu.tdt4250.bg.PatternFilter;
import no.ntnu.tdt4250.bg.Player;
import no.ntnu.tdt4250.bg.RelativeCoordinate;
import no.ntnu.tdt4250.bg.State;
import no.ntnu.tdt4250.bg.StateEffectFilter;
import no.ntnu.tdt4250.bg.Tile;
import no.ntnu.tdt4250.bg.TilePlacement;
import no.ntnu.tdt4250.bg.Transition;
import no.ntnu.tdt4250.bg.bgdsl.services.BgDslGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class BgDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private BgDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == BgPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case BgPackage.BOARD:
				sequence_Board(context, (Board) semanticObject); 
				return; 
			case BgPackage.EFFECT_PIPELINE:
				sequence_EffectPipeline(context, (EffectPipeline) semanticObject); 
				return; 
			case BgPackage.GAME:
				sequence_Game(context, (Game) semanticObject); 
				return; 
			case BgPackage.ITERATIVE_FILTER:
				sequence_IterativeFilter(context, (IterativeFilter) semanticObject); 
				return; 
			case BgPackage.LEGAL_MOVES_PIPELINE:
				sequence_LegalMovesPipeline(context, (LegalMovesPipeline) semanticObject); 
				return; 
			case BgPackage.PATTERN:
				sequence_Pattern(context, (Pattern) semanticObject); 
				return; 
			case BgPackage.PATTERN_FILTER:
				sequence_PatternFilter(context, (PatternFilter) semanticObject); 
				return; 
			case BgPackage.PLAYER:
				sequence_Player(context, (Player) semanticObject); 
				return; 
			case BgPackage.RELATIVE_COORDINATE:
				sequence_RelativeCoordinate(context, (RelativeCoordinate) semanticObject); 
				return; 
			case BgPackage.STATE:
				sequence_State(context, (State) semanticObject); 
				return; 
			case BgPackage.STATE_EFFECT_FILTER:
				sequence_StateEffectFilter(context, (StateEffectFilter) semanticObject); 
				return; 
			case BgPackage.TILE:
				sequence_Tile(context, (Tile) semanticObject); 
				return; 
			case BgPackage.TILE_PLACEMENT:
				sequence_TilePlacement(context, (TilePlacement) semanticObject); 
				return; 
			case BgPackage.TRANSITION:
				sequence_Transition(context, (Transition) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Board returns Board
	 *
	 * Constraint:
	 *     (
	 *         checkered?='checkered' 
	 *         width=EInt 
	 *         height=EInt 
	 *         tiles+=Tile 
	 *         tiles+=Tile* 
	 *         legalMovesPipeline=LegalMovesPipeline? 
	 *         effectPipeline=EffectPipeline? 
	 *         tileplacement+=TilePlacement 
	 *         tileplacement+=TilePlacement*
	 *     )
	 * </pre>
	 */
	protected void sequence_Board(ISerializationContext context, Board semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     EffectPipeline returns EffectPipeline
	 *
	 * Constraint:
	 *     (filters+=Filter filters+=Filter*)?
	 * </pre>
	 */
	protected void sequence_EffectPipeline(ISerializationContext context, EffectPipeline semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Game returns Game
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         turnPolicy=TurnType 
	 *         initialPlayer=[Player|EString] 
	 *         board=Board 
	 *         players+=Player 
	 *         players+=Player*
	 *     )
	 * </pre>
	 */
	protected void sequence_Game(ISerializationContext context, Game semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Filter returns IterativeFilter
	 *     IterativeFilter returns IterativeFilter
	 *
	 * Constraint:
	 *     (name=EString nextFilter=Filter? directionVector=RelativeCoordinate matchRule=Pattern endRule=Pattern)
	 * </pre>
	 */
	protected void sequence_IterativeFilter(ISerializationContext context, IterativeFilter semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     LegalMovesPipeline returns LegalMovesPipeline
	 *
	 * Constraint:
	 *     (filters+=Filter filters+=Filter*)?
	 * </pre>
	 */
	protected void sequence_LegalMovesPipeline(ISerializationContext context, LegalMovesPipeline semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Filter returns PatternFilter
	 *     PatternFilter returns PatternFilter
	 *
	 * Constraint:
	 *     (name=EString nextFilter=Filter? patterns+=Pattern patterns+=Pattern*)
	 * </pre>
	 */
	protected void sequence_PatternFilter(ISerializationContext context, PatternFilter semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Pattern returns Pattern
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         stateSelection=StateSelection? 
	 *         matchState=[State|EString]? 
	 *         relativecoordinates+=RelativeCoordinate 
	 *         relativecoordinates+=RelativeCoordinate*
	 *     )
	 * </pre>
	 */
	protected void sequence_Pattern(ISerializationContext context, Pattern semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Player returns Player
	 *
	 * Constraint:
	 *     (name=EString hexColor=EString associatedState=[State|EString])
	 * </pre>
	 */
	protected void sequence_Player(ISerializationContext context, Player semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BgPackage.Literals.PLAYER__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BgPackage.Literals.PLAYER__NAME));
			if (transientValues.isValueTransient(semanticObject, BgPackage.Literals.PLAYER__HEX_COLOR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BgPackage.Literals.PLAYER__HEX_COLOR));
			if (transientValues.isValueTransient(semanticObject, BgPackage.Literals.PLAYER__ASSOCIATED_STATE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BgPackage.Literals.PLAYER__ASSOCIATED_STATE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPlayerAccess().getNameEStringParserRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getPlayerAccess().getHexColorEStringParserRuleCall_4_0(), semanticObject.getHexColor());
		feeder.accept(grammarAccess.getPlayerAccess().getAssociatedStateStateEStringParserRuleCall_6_0_1(), semanticObject.eGet(BgPackage.Literals.PLAYER__ASSOCIATED_STATE, false));
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     RelativeCoordinate returns RelativeCoordinate
	 *
	 * Constraint:
	 *     (x=EInt y=EInt)
	 * </pre>
	 */
	protected void sequence_RelativeCoordinate(ISerializationContext context, RelativeCoordinate semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BgPackage.Literals.RELATIVE_COORDINATE__X) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BgPackage.Literals.RELATIVE_COORDINATE__X));
			if (transientValues.isValueTransient(semanticObject, BgPackage.Literals.RELATIVE_COORDINATE__Y) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BgPackage.Literals.RELATIVE_COORDINATE__Y));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRelativeCoordinateAccess().getXEIntParserRuleCall_3_0(), semanticObject.getX());
		feeder.accept(grammarAccess.getRelativeCoordinateAccess().getYEIntParserRuleCall_5_0(), semanticObject.getY());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Filter returns StateEffectFilter
	 *     StateEffectFilter returns StateEffectFilter
	 *
	 * Constraint:
	 *     (name=EString stateSelection=StateSelection targetState=[State|EString]? nextFilter=Filter?)
	 * </pre>
	 */
	protected void sequence_StateEffectFilter(ISerializationContext context, StateEffectFilter semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     State returns State
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         hexColor=EString 
	 *         (outbound+=[Transition|EString] outbound+=[Transition|EString]*)? 
	 *         (inbound+=[Transition|EString] inbound+=[Transition|EString]*)?
	 *     )
	 * </pre>
	 */
	protected void sequence_State(ISerializationContext context, State semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TilePlacement returns TilePlacement
	 *
	 * Constraint:
	 *     (row=EInt column=EInt tile=[Tile|EString])
	 * </pre>
	 */
	protected void sequence_TilePlacement(ISerializationContext context, TilePlacement semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BgPackage.Literals.TILE_PLACEMENT__ROW) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BgPackage.Literals.TILE_PLACEMENT__ROW));
			if (transientValues.isValueTransient(semanticObject, BgPackage.Literals.TILE_PLACEMENT__COLUMN) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BgPackage.Literals.TILE_PLACEMENT__COLUMN));
			if (transientValues.isValueTransient(semanticObject, BgPackage.Literals.TILE_PLACEMENT__TILE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BgPackage.Literals.TILE_PLACEMENT__TILE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTilePlacementAccess().getRowEIntParserRuleCall_3_0(), semanticObject.getRow());
		feeder.accept(grammarAccess.getTilePlacementAccess().getColumnEIntParserRuleCall_5_0(), semanticObject.getColumn());
		feeder.accept(grammarAccess.getTilePlacementAccess().getTileTileEStringParserRuleCall_7_0_1(), semanticObject.eGet(BgPackage.Literals.TILE_PLACEMENT__TILE, false));
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Tile returns Tile
	 *
	 * Constraint:
	 *     (
	 *         type=EString 
	 *         hexColor=EString 
	 *         name=EString 
	 *         states+=State 
	 *         states+=State* 
	 *         (transitions+=Transition transitions+=Transition*)? 
	 *         initialState=State
	 *     )
	 * </pre>
	 */
	protected void sequence_Tile(ISerializationContext context, Tile semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Transition returns Transition
	 *
	 * Constraint:
	 *     (name=EString source+=[State|EString] source+=[State|EString]* target=[State|EString])
	 * </pre>
	 */
	protected void sequence_Transition(ISerializationContext context, Transition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
